/**
 * DailyRecommendationsPopup — empathic body↔soul recommendations shown
 * once per day when the user opens the app. Cards are generated by
 * recommendationsEngine based on today's metrics.
 *
 * Tap a card → navigate to the suggested tab/technique.
 * Tap "Not now" → dismiss until tomorrow.
 */

import React, { useEffect, useState } from 'react';
import {
  Modal, View, Text, StyleSheet, TouchableOpacity, ScrollView,
} from 'react-native';
import { COLORS, SPACING } from '../../theme';
import { recommendationsEngine, Recommendation } from '../ai/Recommendations';

interface Props {
  /** Called when the user taps a card. tab + optional params. */
  onNavigate: (tab: string, params?: any) => void;
}

export const DailyRecommendationsPopup: React.FC<Props> = ({ onNavigate }) => {
  const [visible, setVisible] = useState(false);
  const [recs, setRecs] = useState<Recommendation[]>([]);

  useEffect(() => {
    (async () => {
      const should = await recommendationsEngine.shouldShowToday();
      if (!should) return;
      const generated = await recommendationsEngine.generate(3);
      if (generated.length === 0) return; // nothing useful to say today
      setRecs(generated);
      // Small delay so the user lands on the home screen first.
      setTimeout(() => setVisible(true), 1200);
    })();
  }, []);

  const dismiss = async () => {
    setVisible(false);
    await recommendationsEngine.dismissForToday();
  };

  const tapCard = async (rec: Recommendation) => {
    await recommendationsEngine.dismissForToday();
    setVisible(false);
    if (rec.navigateTo) onNavigate(rec.navigateTo.tab, rec.navigateTo.params);
  };

  if (!visible || recs.length === 0) return null;

  return (
    <Modal visible transparent animationType="fade" onRequestClose={dismiss}>
      <View style={styles.overlay}>
        <View style={styles.card}>
          <Text style={styles.preTitle}>FOR YOU TODAY 🪷</Text>
          <Text style={styles.title}>Body & Soul, in conversation</Text>
          <Text style={styles.subtitle}>
            A few empathic suggestions based on what your body whispered today.
          </Text>

          <ScrollView style={{ maxHeight: 380 }} showsVerticalScrollIndicator={false}>
            {recs.map(r => (
              <TouchableOpacity
                key={r.id}
                style={styles.recCard}
                onPress={() => tapCard(r)}
                activeOpacity={0.75}
              >
                <Text style={styles.recIcon}>{r.icon}</Text>
                <View style={{ flex: 1 }}>
                  <Text style={styles.bodyLabel}>BODY</Text>
                  <Text style={styles.bodyText}>{r.bodySignal}</Text>
                  <Text style={styles.soulLabel}>SOUL</Text>
                  <Text style={styles.soulText}>{r.soulResponse}</Text>
                  {r.navigateTo && (
                    <Text style={styles.actionLink}>Tap to open ›</Text>
                  )}
                </View>
              </TouchableOpacity>
            ))}
          </ScrollView>

          <TouchableOpacity style={styles.dismissBtn} onPress={dismiss}>
            <Text style={styles.dismissText}>Not now — thank you 🙏</Text>
          </TouchableOpacity>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  overlay: {
    flex: 1, backgroundColor: 'rgba(0,0,0,0.78)',
    justifyContent: 'center', alignItems: 'center',
    paddingHorizontal: SPACING.md,
  },
  card: {
    width: '100%', maxWidth: 460,
    backgroundColor: COLORS.darkBg, borderRadius: 20,
    padding: SPACING.lg,
    borderWidth: 2, borderColor: 'rgba(212,160,23,0.45)',
  },
  preTitle: {
    fontSize: 11, color: COLORS.gold, fontWeight: '800',
    letterSpacing: 1.5, textAlign: 'center', marginBottom: 4,
  },
  title: {
    fontSize: 20, color: COLORS.cream, fontWeight: '700',
    textAlign: 'center', marginBottom: 6,
  },
  subtitle: {
    fontSize: 12, color: COLORS.muted, lineHeight: 17,
    textAlign: 'center', marginBottom: SPACING.md, fontStyle: 'italic',
  },
  recCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.cardBg, borderRadius: 12,
    padding: SPACING.md, marginBottom: SPACING.sm,
    borderWidth: 1, borderColor: 'rgba(212,160,23,0.2)',
  },
  recIcon: { fontSize: 28, marginRight: SPACING.sm, width: 36 },
  bodyLabel: {
    fontSize: 9, color: COLORS.muted, fontWeight: '700',
    letterSpacing: 1.2, marginBottom: 2,
  },
  bodyText: { fontSize: 13, color: COLORS.cream, fontWeight: '600', marginBottom: 6 },
  soulLabel: {
    fontSize: 9, color: COLORS.gold, fontWeight: '700',
    letterSpacing: 1.2, marginBottom: 2,
  },
  soulText: { fontSize: 13, color: COLORS.cream, lineHeight: 18 },
  actionLink: {
    fontSize: 11, color: COLORS.gold, fontWeight: '700',
    marginTop: 6, textAlign: 'right',
  },
  dismissBtn: {
    marginTop: SPACING.sm, paddingVertical: 10, alignItems: 'center',
  },
  dismissText: {
    color: COLORS.muted, fontSize: 12, textDecorationLine: 'underline',
  },
});
