import { Festival, Deity, HistoryEntry } from './types';

export const FESTIVAL_DB: Record<string, Festival[]> = {
  Hindu: [
    {
      id: 'diwali',
      name: 'Diwali',
      date: '2025-10-20',
      region: 'Hindu',
      wish: 'May the festival of lights bring joy, prosperity & peace! 🪔',
      wishSub: 'Shubh Deepawali 🙏',
      checklist: [
        { id: 1, text: 'Diyas & candles', tag: '🪔' },
        { id: 2, text: 'Rangoli colours', tag: '🎨' },
        { id: 3, text: 'Lakshmi-Ganesha idol', tag: '🙏' },
        { id: 4, text: 'Sweets & mithai box', tag: '🍬' },
        { id: 5, text: 'Puja thali & flowers', tag: '🌺' },
        { id: 6, text: 'Sparklers & firecrackers', tag: '🎆' },
        { id: 7, text: 'New clothes for family', tag: '👗' },
        { id: 8, text: 'Dry fruits gift packs', tag: '🎁' },
      ],
    },
    {
      id: 'navratri',
      name: 'Navratri',
      date: '2025-10-02',
      region: 'Hindu',
      wish: 'Jai Mata Di! May Goddess Durga bless you with strength! 🌸',
      wishSub: 'Shubh Navratri 🙏',
      checklist: [
        { id: 1, text: 'Kumkum & haldi', tag: '🙏' },
        { id: 2, text: 'Marigold & rose flowers', tag: '🌺' },
        { id: 3, text: 'Coconut & betel leaves', tag: '🥥' },
        { id: 4, text: 'Fasting food items', tag: '🍽️' },
        { id: 5, text: 'Garba / dandiya sticks', tag: '💃' },
        { id: 6, text: 'Chaniya choli', tag: '👗' },
        { id: 7, text: 'Ghee & camphor', tag: '🕯️' },
      ],
    },
    {
      id: 'holi',
      name: 'Holi',
      date: '2026-03-14',
      region: 'Hindu',
      wish: 'Wishing you a colourful, joyful Holi! 🌈',
      wishSub: 'Happy Holi 🎨',
      checklist: [
        { id: 1, text: 'Herbal gulal colours', tag: '🎨' },
        { id: 2, text: 'Pichkaris (water guns)', tag: '💦' },
        { id: 3, text: 'Thandai ingredients', tag: '🥛' },
        { id: 4, text: 'Gujiya & sweets', tag: '🍬' },
        { id: 5, text: 'Old clothes to wear', tag: '👕' },
        { id: 6, text: 'Holika dahan wood', tag: '🔥' },
      ],
    },
    {
      id: 'janmashtami',
      name: 'Janmashtami',
      date: '2025-08-16',
      region: 'Hindu',
      wish: 'Jai Shri Krishna! May Lord Krishna fill your life with divine love! 🪈',
      wishSub: 'Shubh Janmashtami 🙏',
      checklist: [
        { id: 1, text: 'Butter & mishri (Makhan)', tag: '🧈' },
        { id: 2, text: 'Krishna idol décor', tag: '🙏' },
        { id: 3, text: 'Yellow & peacock décor', tag: '🦚' },
        { id: 4, text: 'Panchamrit', tag: '🥛' },
        { id: 5, text: 'Cradle for Ladoo Gopal', tag: '🛏️' },
        { id: 6, text: 'Panjiree prasad', tag: '🍬' },
      ],
    },
    {
      id: 'ganeshchaturthi',
      name: 'Ganesh Chaturthi',
      date: '2025-08-27',
      region: 'Hindu',
      wish: 'Ganpati Bappa Morya! May Lord Ganesha remove all obstacles! 🐘',
      wishSub: 'Shubh Ganesh Chaturthi 🙏',
      checklist: [
        { id: 1, text: 'Ganesh idol (eco clay)', tag: '🐘' },
        { id: 2, text: 'Modak & laddoo', tag: '🍬' },
        { id: 3, text: 'Marigold garlands', tag: '🌺' },
        { id: 4, text: 'Red flowers & durva grass', tag: '🌿' },
        { id: 5, text: 'Panchamrit & coconut', tag: '🥥' },
      ],
    },
  ],
  Sikh: [
    {
      id: 'baisakhi',
      name: 'Baisakhi',
      date: '2026-04-14',
      region: 'Sikh',
      wish: 'Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh! Happy Baisakhi! 🌾',
      wishSub: 'Shubh Baisakhi',
      checklist: [
        { id: 1, text: 'Colourful turbans & dupattas', tag: '👗' },
        { id: 2, text: 'Karah prasad ingredients', tag: '🙏' },
        { id: 3, text: 'Bhangra/Giddha dress', tag: '💃' },
        { id: 4, text: 'Langar ingredients', tag: '🍽️' },
      ],
    },
    {
      id: 'gurpurab',
      name: 'Guru Nanak Gurpurab',
      date: '2025-11-05',
      region: 'Sikh',
      wish: "Waheguru Ji's blessings be with you always. Happy Gurpurab! 🙏",
      wishSub: 'Gurpurab Diyan Vadhaiyan',
      checklist: [
        { id: 1, text: 'Karah prasad (suji halwa)', tag: '🙏' },
        { id: 2, text: 'Langar dal & sabzi', tag: '🍽️' },
        { id: 3, text: 'Diyas & candles', tag: '🪔' },
        { id: 4, text: 'White/blue clothes', tag: '👗' },
      ],
    },
  ],
  Muslim: [
    {
      id: 'eid',
      name: 'Eid ul-Fitr',
      date: '2026-03-30',
      region: 'Muslim',
      wish: 'Eid Mubarak! May Allah bless you with happiness & prosperity! 🌙',
      wishSub: 'Eid Mubarak ☪️',
      checklist: [
        { id: 1, text: 'New eid clothes', tag: '👗' },
        { id: 2, text: 'Seviyan & sheer khurma', tag: '🍬' },
        { id: 3, text: 'Eidi envelopes', tag: '💝' },
        { id: 4, text: 'Itar (perfume)', tag: '🌹' },
        { id: 5, text: 'Dates & dry fruits', tag: '🌴' },
        { id: 6, text: 'Gift boxes for family', tag: '🎁' },
      ],
    },
    {
      id: 'eidaladha',
      name: 'Eid ul-Adha',
      date: '2026-06-06',
      region: 'Muslim',
      wish: "Eid ul-Adha Mubarak! May your sacrifice be accepted! 🐑",
      wishSub: 'Eid Mubarak ☪️',
      checklist: [
        { id: 1, text: 'New clothes', tag: '👗' },
        { id: 2, text: 'Qurbani arrangements', tag: '🍖' },
        { id: 3, text: 'Gifts for children', tag: '🎁' },
        { id: 4, text: 'Sewaiyan & halwa', tag: '🍬' },
      ],
    },
  ],
  Christian: [
    {
      id: 'christmas',
      name: 'Christmas',
      date: '2025-12-25',
      region: 'Christian',
      wish: 'Wishing you a blessed Christmas filled with joy & peace! ✨',
      wishSub: 'Merry Christmas 🎄',
      checklist: [
        { id: 1, text: 'Christmas tree & decorations', tag: '🎄' },
        { id: 2, text: 'Nativity scene set', tag: '⭐' },
        { id: 3, text: 'Plum cake & cookies', tag: '🎂' },
        { id: 4, text: 'Gift wrapping supplies', tag: '🎁' },
        { id: 5, text: 'Candles & fairy lights', tag: '🕯️' },
      ],
    },
    {
      id: 'easter',
      name: 'Easter',
      date: '2026-04-05',
      region: 'Christian',
      wish: 'He is Risen! Wishing you a joyful Easter! ✝️',
      wishSub: 'Happy Easter 🐣',
      checklist: [
        { id: 1, text: 'Easter eggs & chocolates', tag: '🥚' },
        { id: 2, text: 'Easter basket', tag: '🎁' },
        { id: 3, text: 'Hot cross buns', tag: '🍞' },
        { id: 4, text: 'Candles for vigil', tag: '🕯️' },
        { id: 5, text: 'New spring clothes', tag: '👗' },
      ],
    },
  ],
};

export const ALL_REGIONS = ['All', 'Hindu', 'Sikh', 'Muslim', 'Christian'] as const;
export const WEEK_DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as const;
export const ICONS = [
  '🙏', '🐘', '🪈', '🌺', '⚡', '🔱', '🦚', '🌙', '☀️', '🪷',
  '🐍', '🦁', '🔔', '🌊', '🕉️', '⚛️', '✡️', '☪️', '✝️', '🪘',
  '🐄', '🦅', '🌸', '🏔️',
];

export const DEFAULT_DEITIES: Deity[] = [
  {
    id: '1',
    name: 'Lord Ganesha',
    icon: '🐘',
    mantra: 'Om Gan Ganapataye Namah',
    prayerAlarm: '06:00',
    alarmOn: true,
    totalMalas: 12,
  },
  {
    id: '2',
    name: 'Lord Krishna',
    icon: '🪈',
    mantra: 'Hare Krishna Hare Rama',
    prayerAlarm: '07:00',
    alarmOn: true,
    totalMalas: 27,
  },
  {
    id: '3',
    name: 'Goddess Lakshmi',
    icon: '🌺',
    mantra: 'Om Shreem Mahalakshmiyei Namah',
    prayerAlarm: '18:00',
    alarmOn: false,
    totalMalas: 8,
  },
];

export const SAMPLE_HISTORY: HistoryEntry[] = [
  { id: 'h1', date: '2025-07-14', deity: 'Lord Ganesha', deityId: '1', malas: 3, japas: 324 },
  { id: 'h2', date: '2025-07-14', deity: 'Lord Krishna', deityId: '2', malas: 5, japas: 540 },
  { id: 'h3', date: '2025-07-13', deity: 'Lord Ganesha', deityId: '1', malas: 2, japas: 216 },
  { id: 'h4', date: '2025-07-12', deity: 'Lord Krishna', deityId: '2', malas: 4, japas: 432 },
  { id: 'h5', date: '2025-07-11', deity: 'Goddess Lakshmi', deityId: '3', malas: 1, japas: 108 },
  { id: 'h6', date: '2025-07-10', deity: 'Lord Ganesha', deityId: '1', malas: 3, japas: 324 },
  { id: 'h7', date: '2025-07-09', deity: 'Lord Krishna', deityId: '2', malas: 2, japas: 216 },
];
