export interface PanchangFestival {
  id: string;
  name: string;
  date: string;
  region: 'Hindu' | 'Sikh' | 'Muslim' | 'Christian';
  deity: string;
  deityIcon: string;
  tithi: string;
  paksha?: string;
  vara: string;
  nakshatra: string;
  month: string;
  significance: string;
  whatToDo: string[];
  timing: string;
  wish: string;
  wishSub: string;
  checklist: { id: number; text: string; tag: string }[];
}

export const PANCHANG_FESTIVALS: PanchangFestival[] = [
  {
    id: 'navratri-day1-2025',
    name: 'Navratri Day 1 — Shailaputri',
    date: '2025-09-22',
    region: 'Hindu',
    deity: 'Maa Shailaputri',
    deityIcon: '🌸',
    tithi: 'Pratipada',
    paksha: 'Shukla',
    vara: 'Somavara (Monday)',
    nakshatra: 'Hasta',
    month: 'Ashwin',
    significance:
      'First day of Sharad Navratri. Worship of Maa Shailaputri, daughter of the Himalayas, who symbolizes purity and devotion.',
    whatToDo: [
      'Ghatasthapana (kalash sthapana) at sunrise',
      'Wear red or yellow clothes',
      'Offer pure ghee to Maa',
      'Recite Durga Saptashati',
      'Begin 9-day fast (vrat)',
    ],
    timing: 'Pratahkaal — 06:00 to 09:00 (best for Ghatasthapana)',
    wish: 'Jai Maa Shailaputri! May the Goddess bless you with strength!',
    wishSub: 'Shubh Navratri 🙏',
    checklist: [
      { id: 1, text: 'Kalash, coconut, mango leaves', tag: '🥥' },
      { id: 2, text: 'Red cloth & sacred thread', tag: '🧵' },
      { id: 3, text: 'Pure ghee (for offering)', tag: '🧈' },
      { id: 4, text: 'Durga Saptashati book', tag: '📖' },
      { id: 5, text: 'Marigold flowers', tag: '🌼' },
      { id: 6, text: 'Akhand jyoti (lamp)', tag: '🪔' },
    ],
  },
  {
    id: 'dussehra-2025',
    name: 'Dussehra (Vijayadashami)',
    date: '2025-10-02',
    region: 'Hindu',
    deity: 'Lord Rama',
    deityIcon: '🏹',
    tithi: 'Dashami',
    paksha: 'Shukla',
    vara: 'Guruvara (Thursday)',
    nakshatra: 'Shravana',
    month: 'Ashwin',
    significance:
      'Victory of Lord Rama over Ravana, symbolizing the triumph of dharma over adharma. Also marks the end of Navratri.',
    whatToDo: [
      'Visit Ramlila / watch Ravana Dahan',
      'Apasmara puja & shastra puja',
      'Cross Shami tree (Shami Pujan)',
      'Take blessings from elders',
      'Distribute Apta leaves (sona patti)',
    ],
    timing: 'Vijaya Muhurat — 14:00 to 14:45 (most auspicious)',
    wish: 'Jai Shri Ram! May righteousness prevail in your life!',
    wishSub: 'Shubh Vijayadashami 🏹',
    checklist: [
      { id: 1, text: 'Apta leaves (sona patti)', tag: '🍃' },
      { id: 2, text: 'Shami branch', tag: '🌿' },
      { id: 3, text: 'Sweets & jalebi', tag: '🍬' },
      { id: 4, text: 'New clothes', tag: '👗' },
      { id: 5, text: 'Tilak & roli', tag: '🔴' },
    ],
  },
  {
    id: 'karwa-chauth-2025',
    name: 'Karwa Chauth',
    date: '2025-10-10',
    region: 'Hindu',
    deity: 'Maa Parvati & Chandra',
    deityIcon: '🌙',
    tithi: 'Chaturthi',
    paksha: 'Krishna',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Rohini',
    month: 'Kartik',
    significance:
      'Married women observe a day-long fast (nirjala vrat) for the long life and well-being of their husbands. Fast is broken after sighting the moon.',
    whatToDo: [
      'Wake before sunrise for Sargi (pre-dawn meal)',
      'Observe nirjala (waterless) fast',
      'Hear the Karwa Chauth katha',
      'Dress in bridal attire (red/maroon)',
      'Offer arghya to moon at moonrise',
    ],
    timing: 'Moonrise — approximately 20:15 (varies by city)',
    wish: 'May your bond be eternal and your love deepen!',
    wishSub: 'Happy Karwa Chauth 🌙',
    checklist: [
      { id: 1, text: 'Sargi thali (from saas)', tag: '🍱' },
      { id: 2, text: 'Karwa (clay pot) with spout', tag: '🏺' },
      { id: 3, text: 'Sieve (chalni)', tag: '🪞' },
      { id: 4, text: 'Mehndi & solah shringar', tag: '💄' },
      { id: 5, text: 'Red bridal saree/lehenga', tag: '👗' },
      { id: 6, text: 'Diya & roli for puja', tag: '🪔' },
    ],
  },
  {
    id: 'dhanteras-2025',
    name: 'Dhanteras',
    date: '2025-10-18',
    region: 'Hindu',
    deity: 'Dhanvantari & Lakshmi',
    deityIcon: '💰',
    tithi: 'Trayodashi',
    paksha: 'Krishna',
    vara: 'Shanivara (Saturday)',
    nakshatra: 'Hasta',
    month: 'Kartik',
    significance:
      'Worship of Lord Dhanvantari (god of Ayurveda) and Goddess Lakshmi. Considered auspicious to buy gold, silver, and utensils on this day.',
    whatToDo: [
      'Buy gold, silver or new utensils',
      'Light 13 diyas at home',
      'Offer prayers to Dhanvantari',
      'Clean and decorate the entrance',
      'Place a Yama-deepam at the doorstep',
    ],
    timing: 'Pradosh Kaal — 17:48 to 20:21 (best for Lakshmi puja)',
    wish: 'May Goddess Lakshmi shower wealth and good health upon you!',
    wishSub: 'Shubh Dhanteras 💰',
    checklist: [
      { id: 1, text: 'New utensils / coin', tag: '🪙' },
      { id: 2, text: '13 diyas (oil lamps)', tag: '🪔' },
      { id: 3, text: 'Marigold & rose petals', tag: '🌺' },
      { id: 4, text: 'Mishri & dhaniya seeds', tag: '🌾' },
      { id: 5, text: 'Lakshmi-Ganesha photo', tag: '🙏' },
      { id: 6, text: 'Broom (signifies prosperity)', tag: '🧹' },
    ],
  },
  {
    id: 'diwali-2025',
    name: 'Diwali (Lakshmi Pujan)',
    date: '2025-10-20',
    region: 'Hindu',
    deity: 'Goddess Lakshmi & Ganesha',
    deityIcon: '🪔',
    tithi: 'Amavasya',
    paksha: 'Krishna',
    vara: 'Somavara (Monday)',
    nakshatra: 'Chitra',
    month: 'Kartik',
    significance:
      'Festival of lights — celebrating Lord Rama’s return to Ayodhya after 14 years. Worship of Goddess Lakshmi for prosperity and Lord Ganesha for wisdom.',
    whatToDo: [
      'Clean the entire house (purification)',
      'Draw rangoli at the entrance',
      'Light diyas in every room',
      'Perform Lakshmi-Ganesha puja in evening',
      'Offer kheel-batashe & sweets',
      'Burst eco-friendly crackers',
    ],
    timing: 'Lakshmi Puja Muhurat — 18:21 to 20:17 (Pradosh Kaal)',
    wish: 'May the festival of lights illuminate your life with joy!',
    wishSub: 'Shubh Deepawali 🪔',
    checklist: [
      { id: 1, text: 'Diyas, candles & fairy lights', tag: '🪔' },
      { id: 2, text: 'Lakshmi-Ganesha murti', tag: '🙏' },
      { id: 3, text: 'Rangoli colours', tag: '🎨' },
      { id: 4, text: 'Kheel, batashe, mishri', tag: '🍬' },
      { id: 5, text: 'Marigold garlands', tag: '🌺' },
      { id: 6, text: 'Fresh kalash with water', tag: '🏺' },
      { id: 7, text: 'New clothes', tag: '👗' },
      { id: 8, text: 'Mithai gift boxes', tag: '🎁' },
    ],
  },
  {
    id: 'govardhan-2025',
    name: 'Govardhan Puja',
    date: '2025-10-22',
    region: 'Hindu',
    deity: 'Lord Krishna',
    deityIcon: '⛰️',
    tithi: 'Pratipada',
    paksha: 'Shukla',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Vishakha',
    month: 'Kartik',
    significance:
      'Commemorates Lord Krishna lifting Govardhan Hill to protect villagers from Indra’s wrath. Annakut (mountain of food) is offered.',
    whatToDo: [
      'Make Govardhan from cow dung or rice',
      'Decorate with flowers',
      'Offer Annakut (56 dishes traditionally)',
      'Worship cows (Gau Puja)',
    ],
    timing: 'Pratahkaal — 06:30 to 08:45',
    wish: 'May Lord Krishna protect and bless your family!',
    wishSub: 'Govardhan Puja Shubhkamna 🐄',
    checklist: [
      { id: 1, text: 'Annakut ingredients', tag: '🍱' },
      { id: 2, text: 'Cow dung (for Govardhan)', tag: '🐄' },
      { id: 3, text: 'Marigolds & tulsi', tag: '🌿' },
      { id: 4, text: 'Mishri & makhan', tag: '🧈' },
    ],
  },
  {
    id: 'bhaidooj-2025',
    name: 'Bhai Dooj',
    date: '2025-10-23',
    region: 'Hindu',
    deity: 'Yamuna & Yamraj',
    deityIcon: '🤝',
    tithi: 'Dwitiya',
    paksha: 'Shukla',
    vara: 'Guruvara (Thursday)',
    nakshatra: 'Anuradha',
    month: 'Kartik',
    significance:
      'Sister applies tilak on brother’s forehead and prays for his long life. Brother gives gifts and vows to protect her.',
    whatToDo: [
      'Sister prepares thali with tilak, sweets, diya',
      'Apply tilak with rice and roli',
      'Brother takes the vow of protection',
      'Exchange gifts and sweets',
    ],
    timing: 'Aparahna — 13:18 to 15:33 (most auspicious)',
    wish: 'May the bond of love between siblings flourish!',
    wishSub: 'Happy Bhai Dooj 🤝',
    checklist: [
      { id: 1, text: 'Tilak thali & roli', tag: '🔴' },
      { id: 2, text: 'Sweets & dry fruits', tag: '🍬' },
      { id: 3, text: 'Diya & cotton wick', tag: '🪔' },
      { id: 4, text: 'Gift for brother/sister', tag: '🎁' },
    ],
  },
  {
    id: 'tulsi-vivah-2025',
    name: 'Tulsi Vivah',
    date: '2025-11-02',
    region: 'Hindu',
    deity: 'Tulsi & Shaligram',
    deityIcon: '🌿',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Ravivara (Sunday)',
    nakshatra: 'Shravana',
    month: 'Kartik',
    significance:
      'Ceremonial marriage of Tulsi plant with Lord Vishnu (Shaligram). Marks the start of Hindu wedding season.',
    whatToDo: [
      'Decorate Tulsi plant with sari and ornaments',
      'Perform marriage rituals',
      'Offer sugarcane and amla',
      'Distribute prasad',
    ],
    timing: 'Pradosh Kaal — 17:36 to 20:08',
    wish: 'May Tulsi Maa bring purity and prosperity!',
    wishSub: 'Shubh Tulsi Vivah 🌿',
    checklist: [
      { id: 1, text: 'Tulsi pot decoration', tag: '🌿' },
      { id: 2, text: 'Red chunari & bindi', tag: '🧣' },
      { id: 3, text: 'Sugarcane & amla', tag: '🍬' },
      { id: 4, text: 'Shaligram or Vishnu idol', tag: '🙏' },
    ],
  },
  {
    id: 'kartik-purnima-2025',
    name: 'Kartik Purnima (Dev Diwali)',
    date: '2025-11-05',
    region: 'Hindu',
    deity: 'Lord Vishnu & Shiva',
    deityIcon: '🌕',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Krittika',
    month: 'Kartik',
    significance:
      'Holiest full moon — Lord Shiva killed demon Tripurasura. Celebrated as Dev Diwali in Varanasi with thousands of diyas on ghats.',
    whatToDo: [
      'Holy bath in Ganga / sacred river',
      'Light deepdaan (floating lamps)',
      'Visit Shiva or Vishnu temple',
      'Perform Satyanarayan katha',
    ],
    timing: 'Sandhya Kaal — 17:45 onwards (for deepdaan)',
    wish: 'May the divine light illuminate every corner of your life!',
    wishSub: 'Shubh Kartik Purnima 🌕',
    checklist: [
      { id: 1, text: 'Deep daan (lamps to float)', tag: '🪔' },
      { id: 2, text: 'Ghee & camphor', tag: '🕯️' },
      { id: 3, text: 'Satyanarayan prasad', tag: '🍬' },
      { id: 4, text: 'White flowers', tag: '🌼' },
    ],
  },
  {
    id: 'gurpurab-2025',
    name: 'Guru Nanak Jayanti',
    date: '2025-11-05',
    region: 'Sikh',
    deity: 'Guru Nanak Dev Ji',
    deityIcon: '🙏',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Krittika',
    month: 'Kartik',
    significance:
      '556th birth anniversary of Guru Nanak Dev Ji, founder of Sikhism. Celebrated with prabhat pheri, akhand path and langar.',
    whatToDo: [
      'Attend prabhat pheri (early morning procession)',
      'Visit Gurudwara for path',
      'Listen to kirtan',
      'Serve & eat langar',
      'Read Japji Sahib',
    ],
    timing: 'Amrit Vela — 03:00 to 06:00 (most blessed)',
    wish: "Waheguru Ji's blessings be with you always!",
    wishSub: 'Gurpurab Diyan Vadhaiyan 🙏',
    checklist: [
      { id: 1, text: 'Karah prasad (suji halwa)', tag: '🙏' },
      { id: 2, text: 'Langar dal & sabzi', tag: '🍽️' },
      { id: 3, text: 'White/blue clothes', tag: '👗' },
      { id: 4, text: 'Diyas & candles', tag: '🪔' },
    ],
  },
  {
    id: 'pongal-2026',
    name: 'Pongal / Makar Sankranti',
    date: '2026-01-14',
    region: 'Hindu',
    deity: 'Surya Bhagwan',
    deityIcon: '☀️',
    tithi: 'Saptami',
    paksha: 'Krishna',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Hasta',
    month: 'Pausha',
    significance:
      'Sun’s transit into Capricorn (Makar). Marks end of winter solstice and beginning of harvest season.',
    whatToDo: [
      'Holy dip at sunrise',
      'Make Pongal/khichdi from new harvest',
      'Donate til (sesame), gud (jaggery), woollen clothes',
      'Fly kites',
      'Offer arghya to Sun',
    ],
    timing: 'Punya Kaal — 07:15 to 12:30',
    wish: 'May the Sun bless you with warmth and abundance!',
    wishSub: 'Happy Makar Sankranti ☀️',
    checklist: [
      { id: 1, text: 'Til, gud, rice', tag: '🌾' },
      { id: 2, text: 'New clay pot (for Pongal)', tag: '🏺' },
      { id: 3, text: 'Sugarcane', tag: '🌿' },
      { id: 4, text: 'Kites & manjha', tag: '🪁' },
      { id: 5, text: 'Donation items', tag: '🎁' },
    ],
  },
  {
    id: 'mahashivratri-2026',
    name: 'Maha Shivratri',
    date: '2026-02-15',
    region: 'Hindu',
    deity: 'Lord Shiva',
    deityIcon: '🔱',
    tithi: 'Chaturdashi',
    paksha: 'Krishna',
    vara: 'Ravivara (Sunday)',
    nakshatra: 'Shravana',
    month: 'Phalguna',
    significance:
      'The great night of Shiva — celebrates the cosmic dance of Shiva (Tandava) and his marriage with Parvati.',
    whatToDo: [
      'Observe day-long fast (phalahar)',
      'Visit Shiva temple',
      'Offer bel patra, milk, water on Shivling',
      'Chant Om Namah Shivaya',
      'Stay awake all night for jagran',
    ],
    timing: '4 prahar puja — 18:00, 21:00, 00:00, 03:00',
    wish: 'Har Har Mahadev! May Lord Shiva bless you!',
    wishSub: 'Shubh Maha Shivratri 🔱',
    checklist: [
      { id: 1, text: 'Bel patra (3-leaf)', tag: '🍃' },
      { id: 2, text: 'Milk, dahi, ghee, honey', tag: '🥛' },
      { id: 3, text: 'Datura & dhatura flower', tag: '🌸' },
      { id: 4, text: 'Bhasma (sacred ash)', tag: '🪨' },
      { id: 5, text: 'Rudraksha mala', tag: '📿' },
      { id: 6, text: 'Phalahar (vrat food)', tag: '🍎' },
    ],
  },
  {
    id: 'holi-2026',
    name: 'Holi (Rangwali)',
    date: '2026-03-14',
    region: 'Hindu',
    deity: 'Krishna & Radha',
    deityIcon: '🎨',
    tithi: 'Pratipada',
    paksha: 'Krishna',
    vara: 'Shanivara (Saturday)',
    nakshatra: 'Uttara Phalguni',
    month: 'Chaitra',
    significance:
      'Festival of colours celebrating victory of good over evil (Prahlad & Holika story). Day after Holika Dahan.',
    whatToDo: [
      'Holika Dahan on previous evening',
      'Apply gulal to family & friends',
      'Sing & dance to Holi songs',
      'Eat gujiya, thandai, dahi vada',
    ],
    timing: 'Holika Dahan — Pradosh Kaal previous day; Color play — morning',
    wish: 'May your life be filled with vibrant colours of joy!',
    wishSub: 'Happy Holi 🎨',
    checklist: [
      { id: 1, text: 'Herbal gulal & rang', tag: '🎨' },
      { id: 2, text: 'Pichkari (water gun)', tag: '💦' },
      { id: 3, text: 'Thandai ingredients', tag: '🥛' },
      { id: 4, text: 'Gujiya & dahi bhalla', tag: '🍬' },
      { id: 5, text: 'Old white clothes', tag: '👕' },
      { id: 6, text: 'Holika dahan wood', tag: '🔥' },
    ],
  },
  {
    id: 'ramnavami-2026',
    name: 'Rama Navami',
    date: '2026-03-26',
    region: 'Hindu',
    deity: 'Lord Rama',
    deityIcon: '🏹',
    tithi: 'Navami',
    paksha: 'Shukla',
    vara: 'Guruvara (Thursday)',
    nakshatra: 'Punarvasu',
    month: 'Chaitra',
    significance:
      'Birth of Lord Rama, the seventh avatar of Vishnu. Climax of Chaitra Navratri.',
    whatToDo: [
      'Recite Ramayan / Sundar Kand',
      'Fast and offer prasad at noon',
      'Visit Ram temple',
      'Sing bhajans & kirtan',
    ],
    timing: 'Madhyahna — 11:00 to 13:30 (Lord Rama’s birth time)',
    wish: 'Jai Shri Ram! May Lord Rama’s grace be upon you!',
    wishSub: 'Shubh Ram Navami 🏹',
    checklist: [
      { id: 1, text: 'Ram darbar photo / idol', tag: '🙏' },
      { id: 2, text: 'Tulsi & yellow flowers', tag: '🌼' },
      { id: 3, text: 'Panchamrit', tag: '🥛' },
      { id: 4, text: 'Sundar Kand book', tag: '📖' },
      { id: 5, text: 'Kheer / panjiri prasad', tag: '🍬' },
    ],
  },
  {
    id: 'eid-2026',
    name: 'Eid ul-Fitr',
    date: '2026-03-30',
    region: 'Muslim',
    deity: 'Allah',
    deityIcon: '🌙',
    tithi: 'Shawwal 1',
    vara: 'Somavara (Monday)',
    nakshatra: '—',
    month: 'Shawwal (Hijri)',
    significance:
      'Marks the end of Ramadan, the holy month of fasting. A celebration of gratitude and charity.',
    whatToDo: [
      'Pay Zakat al-Fitr before Eid prayer',
      'Eid namaz at masjid',
      'Wear new clothes',
      'Greet "Eid Mubarak"',
      'Visit family, distribute Eidi',
    ],
    timing: 'Eid namaz — after sunrise (around 06:30)',
    wish: 'Eid Mubarak! May Allah bless you with happiness!',
    wishSub: 'Eid Mubarak ☪️',
    checklist: [
      { id: 1, text: 'New eid clothes', tag: '👗' },
      { id: 2, text: 'Sheer khurma & sevaiyan', tag: '🍬' },
      { id: 3, text: 'Eidi envelopes', tag: '💝' },
      { id: 4, text: 'Itar (perfume)', tag: '🌹' },
      { id: 5, text: 'Dates & dry fruits', tag: '🌴' },
      { id: 6, text: 'Zakat amount', tag: '🤲' },
    ],
  },
  {
    id: 'easter-2026',
    name: 'Easter Sunday',
    date: '2026-04-05',
    region: 'Christian',
    deity: 'Jesus Christ',
    deityIcon: '✝️',
    tithi: '—',
    vara: 'Ravivara (Sunday)',
    nakshatra: '—',
    month: 'April',
    significance:
      'Resurrection of Jesus Christ from the dead. Most important Christian festival celebrating victory of life over death.',
    whatToDo: [
      'Attend Easter Sunday mass',
      'Light Paschal candle',
      'Easter egg hunt with children',
      'Family feast',
      'Greet "He is Risen!"',
    ],
    timing: 'Sunrise service — 05:30 to 07:00',
    wish: 'He is Risen! May joy and hope fill your heart!',
    wishSub: 'Happy Easter 🐣',
    checklist: [
      { id: 1, text: 'Easter eggs & chocolates', tag: '🥚' },
      { id: 2, text: 'Easter basket', tag: '🎁' },
      { id: 3, text: 'Hot cross buns', tag: '🍞' },
      { id: 4, text: 'Paschal candles', tag: '🕯️' },
      { id: 5, text: 'New spring clothes', tag: '👗' },
    ],
  },
  {
    id: 'baisakhi-2026',
    name: 'Baisakhi',
    date: '2026-04-14',
    region: 'Sikh',
    deity: 'Guru Gobind Singh & Khalsa',
    deityIcon: '🌾',
    tithi: 'Pratipada',
    paksha: 'Shukla',
    vara: 'Mangalvara (Tuesday)',
    nakshatra: 'Ashwini',
    month: 'Vaisakha',
    significance:
      'Birth of the Khalsa Panth in 1699 by Guru Gobind Singh Ji. Also celebrates spring harvest.',
    whatToDo: [
      'Visit Gurudwara at amrit vela',
      'Listen to Guru Granth Sahib path',
      'Bhangra/Giddha celebration',
      'Wear traditional Punjabi attire',
      'Serve langar',
    ],
    timing: 'Amrit Vela — 03:00 to 06:00',
    wish: 'Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh!',
    wishSub: 'Happy Baisakhi 🌾',
    checklist: [
      { id: 1, text: 'Colourful turbans & dupatte', tag: '👗' },
      { id: 2, text: 'Karah prasad', tag: '🙏' },
      { id: 3, text: 'Langar ingredients', tag: '🍽️' },
      { id: 4, text: 'Dholki / dhol', tag: '🪘' },
    ],
  },
  {
    id: 'akshaya-tritiya-2026',
    name: 'Akshaya Tritiya',
    date: '2026-04-20',
    region: 'Hindu',
    deity: 'Lakshmi & Vishnu',
    deityIcon: '💎',
    tithi: 'Tritiya',
    paksha: 'Shukla',
    vara: 'Somavara (Monday)',
    nakshatra: 'Rohini',
    month: 'Vaisakha',
    significance:
      'One of 4 most auspicious days. "Akshaya" means imperishable — any good deed multiplies infinitely. Best day to buy gold.',
    whatToDo: [
      'Buy gold, silver, or property',
      'Donate to needy (annadaan)',
      'Lakshmi-Narayan puja',
      'Recite Vishnu Sahasranama',
      'Begin new ventures',
    ],
    timing: 'Whole day auspicious; best 05:45 to 12:18',
    wish: 'May this Akshaya Tritiya bring eternal prosperity!',
    wishSub: 'Shubh Akshaya Tritiya 💎',
    checklist: [
      { id: 1, text: 'Gold/silver coin', tag: '🪙' },
      { id: 2, text: 'Tulsi leaves', tag: '🌿' },
      { id: 3, text: 'Yellow flowers', tag: '🌼' },
      { id: 4, text: 'Donation items (food/clothes)', tag: '🎁' },
    ],
  },
  {
    id: 'eid-al-adha-2026',
    name: 'Eid ul-Adha (Bakrid)',
    date: '2026-06-06',
    region: 'Muslim',
    deity: 'Allah',
    deityIcon: '🐑',
    tithi: 'Dhul-Hijjah 10',
    vara: 'Shanivara (Saturday)',
    nakshatra: '—',
    month: 'Dhul-Hijjah (Hijri)',
    significance:
      'Festival of Sacrifice — commemorates Prophet Ibrahim’s willingness to sacrifice his son for Allah. Climax of Hajj pilgrimage.',
    whatToDo: [
      'Eid namaz at masjid',
      'Qurbani (animal sacrifice)',
      'Distribute meat in 3 parts (family/friends/poor)',
      'Visit relatives',
      'Wear new clothes',
    ],
    timing: 'Eid namaz — after sunrise (around 06:00)',
    wish: 'Eid ul-Adha Mubarak! May your sacrifice be accepted!',
    wishSub: 'Eid Mubarak ☪️',
    checklist: [
      { id: 1, text: 'New clothes', tag: '👗' },
      { id: 2, text: 'Qurbani arrangements', tag: '🍖' },
      { id: 3, text: 'Sevaiyan & halwa', tag: '🍬' },
      { id: 4, text: 'Gifts for children', tag: '🎁' },
    ],
  },
  {
    id: 'guru-purnima-2026',
    name: 'Guru Purnima',
    date: '2026-07-29',
    region: 'Hindu',
    deity: 'Guru / Vyasa',
    deityIcon: '📖',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Uttara Ashadha',
    month: 'Ashadha',
    significance:
      'Honors all spiritual gurus and Maharishi Vyasa, who composed the Vedas. Day to express gratitude to teachers.',
    whatToDo: [
      'Take blessings from your guru',
      'Read scriptures (Gita / Vedas)',
      'Practice extra meditation',
      'Donate to ashram or seva',
      'Recite Guru mantra 108 times',
    ],
    timing: 'Brahma Muhurta — 04:15 to 05:45',
    wish: 'Pranam to all gurus who light our path!',
    wishSub: 'Guru Purnima Shubhkamna 📖',
    checklist: [
      { id: 1, text: 'Guru padukas / photo', tag: '🙏' },
      { id: 2, text: 'White flowers', tag: '🌼' },
      { id: 3, text: 'Sweets for offering', tag: '🍬' },
      { id: 4, text: 'Bhagavad Gita / Vedas', tag: '📖' },
    ],
  },
  {
    id: 'janmashtami-2026',
    name: 'Krishna Janmashtami',
    date: '2026-09-04',
    region: 'Hindu',
    deity: 'Lord Krishna',
    deityIcon: '🪈',
    tithi: 'Ashtami',
    paksha: 'Krishna',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Rohini',
    month: 'Bhadrapada',
    significance:
      'Birth of Lord Krishna, the 8th avatar of Vishnu. Born at midnight in Mathura prison to Devaki and Vasudeva.',
    whatToDo: [
      'Day-long fast (vrat)',
      'Decorate Krishna jhanki / cradle',
      'Sing bhajans till midnight',
      'Break fast with Panjiri prasad after midnight aarti',
      'Visit Krishna temple',
    ],
    timing: 'Nishita Kaal — 23:42 to 00:25 (midnight, Krishna’s birth)',
    wish: 'Jai Shri Krishna! May Lord Krishna fill your life with love!',
    wishSub: 'Shubh Janmashtami 🪈',
    checklist: [
      { id: 1, text: 'Cradle (jhula) for Ladoo Gopal', tag: '🛏️' },
      { id: 2, text: 'Butter, mishri, makhan', tag: '🧈' },
      { id: 3, text: 'Yellow & peacock decor', tag: '🦚' },
      { id: 4, text: 'Tulsi leaves', tag: '🌿' },
      { id: 5, text: 'Panchamrit & panjiri', tag: '🍬' },
      { id: 6, text: 'Flute (bansuri)', tag: '🪈' },
    ],
  },
  {
    id: 'ganesh-chaturthi-2026',
    name: 'Ganesh Chaturthi',
    date: '2026-09-15',
    region: 'Hindu',
    deity: 'Lord Ganesha',
    deityIcon: '🐘',
    tithi: 'Chaturthi',
    paksha: 'Shukla',
    vara: 'Mangalvara (Tuesday)',
    nakshatra: 'Hasta',
    month: 'Bhadrapada',
    significance:
      'Birth of Lord Ganesha, the remover of obstacles. 10-day festival ending with Anant Chaturdashi visarjan.',
    whatToDo: [
      'Sthapana (installation) at sunrise',
      'Daily aarti morning & evening',
      'Offer 21 modaks',
      'Avoid sighting moon (Mithya Dosha)',
      'Visarjan on Anant Chaturdashi (after 10 days)',
    ],
    timing: 'Madhyahna — 11:01 to 13:28 (best for sthapana)',
    wish: 'Ganpati Bappa Morya! May Ganesha remove all obstacles!',
    wishSub: 'Shubh Ganesh Chaturthi 🐘',
    checklist: [
      { id: 1, text: 'Eco-clay Ganesha idol', tag: '🐘' },
      { id: 2, text: 'Modak (21 pieces)', tag: '🍬' },
      { id: 3, text: 'Durva grass (21 strands)', tag: '🌿' },
      { id: 4, text: 'Red flowers (jaswand)', tag: '🌺' },
      { id: 5, text: 'Panchamrit & coconut', tag: '🥥' },
      { id: 6, text: 'Dhup, deep, kapur', tag: '🪔' },
    ],
  },
  {
    id: 'christmas-2025',
    name: 'Christmas',
    date: '2025-12-25',
    region: 'Christian',
    deity: 'Jesus Christ',
    deityIcon: '🎄',
    tithi: '—',
    vara: 'Guruvara (Thursday)',
    nakshatra: '—',
    month: 'December',
    significance:
      'Birth of Jesus Christ, the Son of God. Celebrated worldwide as a festival of peace, love and giving.',
    whatToDo: [
      'Attend midnight mass',
      'Decorate Christmas tree',
      'Set up nativity scene',
      'Exchange gifts',
      'Sing carols & enjoy feast',
    ],
    timing: 'Midnight mass — 23:00 to 00:30',
    wish: 'Wishing you a blessed Christmas filled with joy & peace!',
    wishSub: 'Merry Christmas 🎄',
    checklist: [
      { id: 1, text: 'Christmas tree & ornaments', tag: '🎄' },
      { id: 2, text: 'Nativity scene set', tag: '⭐' },
      { id: 3, text: 'Plum cake & cookies', tag: '🎂' },
      { id: 4, text: 'Gift wrapping supplies', tag: '🎁' },
      { id: 5, text: 'Candles & fairy lights', tag: '🕯️' },
      { id: 6, text: 'Stockings & santa hat', tag: '🎅' },
    ],
  },
];

export const REGIONS = ['All', 'Hindu', 'Sikh', 'Muslim', 'Christian'] as const;
