export interface PanchangFestival {
  id: string;
  name: string;
  date: string;
  region: 'Hindu' | 'Sikh' | 'Muslim' | 'Christian';
  deity: string;
  deityIcon: string;
  tithi: string;
  paksha?: string;
  vara: string;
  nakshatra: string;
  month: string;
  significance: string;
  whatToDo: string[];
  timing: string;
  poojaTimings?: { label: string; from: string; to: string }[];
  vrataInfo?: string;
  fromTime?: string;
  toTime?: string;
  wish: string;
  wishSub: string;
  checklist: { id: number; text: string; tag: string }[];
}

export const PANCHANG_FESTIVALS: PanchangFestival[] = [
  {
    id: 'navratri-day1-2025',
    name: 'Navratri Day 1 — Shailaputri',
    date: '2025-09-22',
    region: 'Hindu',
    deity: 'Maa Shailaputri',
    deityIcon: '🌸',
    tithi: 'Pratipada',
    paksha: 'Shukla',
    vara: 'Somavara (Monday)',
    nakshatra: 'Hasta',
    month: 'Ashwin',
    significance:
      'First day of Sharad Navratri. Worship of Maa Shailaputri, daughter of the Himalayas, who symbolizes purity and devotion.',
    whatToDo: [
      'Ghatasthapana (kalash sthapana) at sunrise',
      'Wear red or yellow clothes',
      'Offer pure ghee to Maa',
      'Recite Durga Saptashati',
      'Begin 9-day fast (vrat)',
    ],
    timing: 'Pratahkaal — 06:00 to 09:00 (best for Ghatasthapana)',
    wish: 'Jai Maa Shailaputri! May the Goddess bless you with strength!',
    wishSub: 'Shubh Navratri 🙏',
    checklist: [
      { id: 1, text: 'Kalash, coconut, mango leaves', tag: '🥥' },
      { id: 2, text: 'Red cloth & sacred thread', tag: '🧵' },
      { id: 3, text: 'Pure ghee (for offering)', tag: '🧈' },
      { id: 4, text: 'Durga Saptashati book', tag: '📖' },
      { id: 5, text: 'Marigold flowers', tag: '🌼' },
      { id: 6, text: 'Akhand jyoti (lamp)', tag: '🪔' },
    ],
  },
  {
    id: 'dussehra-2025',
    name: 'Dussehra (Vijayadashami)',
    date: '2025-10-02',
    region: 'Hindu',
    deity: 'Lord Rama',
    deityIcon: '🏹',
    tithi: 'Dashami',
    paksha: 'Shukla',
    vara: 'Guruvara (Thursday)',
    nakshatra: 'Shravana',
    month: 'Ashwin',
    significance:
      'Victory of Lord Rama over Ravana, symbolizing the triumph of dharma over adharma. Also marks the end of Navratri.',
    whatToDo: [
      'Visit Ramlila / watch Ravana Dahan',
      'Apasmara puja & shastra puja',
      'Cross Shami tree (Shami Pujan)',
      'Take blessings from elders',
      'Distribute Apta leaves (sona patti)',
    ],
    timing: 'Vijaya Muhurat — 14:00 to 14:45 (most auspicious)',
    wish: 'Jai Shri Ram! May righteousness prevail in your life!',
    wishSub: 'Shubh Vijayadashami 🏹',
    checklist: [
      { id: 1, text: 'Apta leaves (sona patti)', tag: '🍃' },
      { id: 2, text: 'Shami branch', tag: '🌿' },
      { id: 3, text: 'Sweets & jalebi', tag: '🍬' },
      { id: 4, text: 'New clothes', tag: '👗' },
      { id: 5, text: 'Tilak & roli', tag: '🔴' },
    ],
  },
  {
    id: 'karwa-chauth-2025',
    name: 'Karwa Chauth',
    date: '2025-10-10',
    region: 'Hindu',
    deity: 'Maa Parvati & Chandra',
    deityIcon: '🌙',
    tithi: 'Chaturthi',
    paksha: 'Krishna',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Rohini',
    month: 'Kartik',
    significance:
      'Married women observe a day-long fast (nirjala vrat) for the long life and well-being of their husbands. Fast is broken after sighting the moon.',
    whatToDo: [
      'Wake before sunrise for Sargi (pre-dawn meal)',
      'Observe nirjala (waterless) fast',
      'Hear the Karwa Chauth katha',
      'Dress in bridal attire (red/maroon)',
      'Offer arghya to moon at moonrise',
    ],
    timing: 'Moonrise — approximately 20:15 (varies by city)',
    wish: 'May your bond be eternal and your love deepen!',
    wishSub: 'Happy Karwa Chauth 🌙',
    checklist: [
      { id: 1, text: 'Sargi thali (from saas)', tag: '🍱' },
      { id: 2, text: 'Karwa (clay pot) with spout', tag: '🏺' },
      { id: 3, text: 'Sieve (chalni)', tag: '🪞' },
      { id: 4, text: 'Mehndi & solah shringar', tag: '💄' },
      { id: 5, text: 'Red bridal saree/lehenga', tag: '👗' },
      { id: 6, text: 'Diya & roli for puja', tag: '🪔' },
    ],
  },
  {
    id: 'dhanteras-2025',
    name: 'Dhanteras',
    date: '2025-10-18',
    region: 'Hindu',
    deity: 'Dhanvantari & Lakshmi',
    deityIcon: '💰',
    tithi: 'Trayodashi',
    paksha: 'Krishna',
    vara: 'Shanivara (Saturday)',
    nakshatra: 'Hasta',
    month: 'Kartik',
    significance:
      'Worship of Lord Dhanvantari (god of Ayurveda) and Goddess Lakshmi. Considered auspicious to buy gold, silver, and utensils on this day.',
    whatToDo: [
      'Buy gold, silver or new utensils',
      'Light 13 diyas at home',
      'Offer prayers to Dhanvantari',
      'Clean and decorate the entrance',
      'Place a Yama-deepam at the doorstep',
    ],
    timing: 'Pradosh Kaal — 17:48 to 20:21 (best for Lakshmi puja)',
    wish: 'May Goddess Lakshmi shower wealth and good health upon you!',
    wishSub: 'Shubh Dhanteras 💰',
    checklist: [
      { id: 1, text: 'New utensils / coin', tag: '🪙' },
      { id: 2, text: '13 diyas (oil lamps)', tag: '🪔' },
      { id: 3, text: 'Marigold & rose petals', tag: '🌺' },
      { id: 4, text: 'Mishri & dhaniya seeds', tag: '🌾' },
      { id: 5, text: 'Lakshmi-Ganesha photo', tag: '🙏' },
      { id: 6, text: 'Broom (signifies prosperity)', tag: '🧹' },
    ],
  },
  {
    id: 'diwali-2025',
    name: 'Diwali (Lakshmi Pujan)',
    date: '2025-10-20',
    region: 'Hindu',
    deity: 'Goddess Lakshmi & Ganesha',
    deityIcon: '🪔',
    tithi: 'Amavasya',
    paksha: 'Krishna',
    vara: 'Somavara (Monday)',
    nakshatra: 'Chitra',
    month: 'Kartik',
    significance:
      'Festival of lights — celebrating Lord Rama’s return to Ayodhya after 14 years. Worship of Goddess Lakshmi for prosperity and Lord Ganesha for wisdom.',
    whatToDo: [
      'Clean the entire house (purification)',
      'Draw rangoli at the entrance',
      'Light diyas in every room',
      'Perform Lakshmi-Ganesha puja in evening',
      'Offer kheel-batashe & sweets',
      'Burst eco-friendly crackers',
    ],
    timing: 'Lakshmi Puja Muhurat — 18:21 to 20:17 (Pradosh Kaal)',
    wish: 'May the festival of lights illuminate your life with joy!',
    wishSub: 'Shubh Deepawali 🪔',
    checklist: [
      { id: 1, text: 'Diyas, candles & fairy lights', tag: '🪔' },
      { id: 2, text: 'Lakshmi-Ganesha murti', tag: '🙏' },
      { id: 3, text: 'Rangoli colours', tag: '🎨' },
      { id: 4, text: 'Kheel, batashe, mishri', tag: '🍬' },
      { id: 5, text: 'Marigold garlands', tag: '🌺' },
      { id: 6, text: 'Fresh kalash with water', tag: '🏺' },
      { id: 7, text: 'New clothes', tag: '👗' },
      { id: 8, text: 'Mithai gift boxes', tag: '🎁' },
    ],
  },
  {
    id: 'govardhan-2025',
    name: 'Govardhan Puja',
    date: '2025-10-22',
    region: 'Hindu',
    deity: 'Lord Krishna',
    deityIcon: '⛰️',
    tithi: 'Pratipada',
    paksha: 'Shukla',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Vishakha',
    month: 'Kartik',
    significance:
      'Commemorates Lord Krishna lifting Govardhan Hill to protect villagers from Indra’s wrath. Annakut (mountain of food) is offered.',
    whatToDo: [
      'Make Govardhan from cow dung or rice',
      'Decorate with flowers',
      'Offer Annakut (56 dishes traditionally)',
      'Worship cows (Gau Puja)',
    ],
    timing: 'Pratahkaal — 06:30 to 08:45',
    wish: 'May Lord Krishna protect and bless your family!',
    wishSub: 'Govardhan Puja Shubhkamna 🐄',
    checklist: [
      { id: 1, text: 'Annakut ingredients', tag: '🍱' },
      { id: 2, text: 'Cow dung (for Govardhan)', tag: '🐄' },
      { id: 3, text: 'Marigolds & tulsi', tag: '🌿' },
      { id: 4, text: 'Mishri & makhan', tag: '🧈' },
    ],
  },
  {
    id: 'bhaidooj-2025',
    name: 'Bhai Dooj',
    date: '2025-10-23',
    region: 'Hindu',
    deity: 'Yamuna & Yamraj',
    deityIcon: '🤝',
    tithi: 'Dwitiya',
    paksha: 'Shukla',
    vara: 'Guruvara (Thursday)',
    nakshatra: 'Anuradha',
    month: 'Kartik',
    significance:
      'Sister applies tilak on brother’s forehead and prays for his long life. Brother gives gifts and vows to protect her.',
    whatToDo: [
      'Sister prepares thali with tilak, sweets, diya',
      'Apply tilak with rice and roli',
      'Brother takes the vow of protection',
      'Exchange gifts and sweets',
    ],
    timing: 'Aparahna — 13:18 to 15:33 (most auspicious)',
    wish: 'May the bond of love between siblings flourish!',
    wishSub: 'Happy Bhai Dooj 🤝',
    checklist: [
      { id: 1, text: 'Tilak thali & roli', tag: '🔴' },
      { id: 2, text: 'Sweets & dry fruits', tag: '🍬' },
      { id: 3, text: 'Diya & cotton wick', tag: '🪔' },
      { id: 4, text: 'Gift for brother/sister', tag: '🎁' },
    ],
  },
  {
    id: 'tulsi-vivah-2025',
    name: 'Tulsi Vivah',
    date: '2025-11-02',
    region: 'Hindu',
    deity: 'Tulsi & Shaligram',
    deityIcon: '🌿',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Ravivara (Sunday)',
    nakshatra: 'Shravana',
    month: 'Kartik',
    significance:
      'Ceremonial marriage of Tulsi plant with Lord Vishnu (Shaligram). Marks the start of Hindu wedding season.',
    whatToDo: [
      'Decorate Tulsi plant with sari and ornaments',
      'Perform marriage rituals',
      'Offer sugarcane and amla',
      'Distribute prasad',
    ],
    timing: 'Pradosh Kaal — 17:36 to 20:08',
    wish: 'May Tulsi Maa bring purity and prosperity!',
    wishSub: 'Shubh Tulsi Vivah 🌿',
    checklist: [
      { id: 1, text: 'Tulsi pot decoration', tag: '🌿' },
      { id: 2, text: 'Red chunari & bindi', tag: '🧣' },
      { id: 3, text: 'Sugarcane & amla', tag: '🍬' },
      { id: 4, text: 'Shaligram or Vishnu idol', tag: '🙏' },
    ],
  },
  {
    id: 'kartik-purnima-2025',
    name: 'Kartik Purnima (Dev Diwali)',
    date: '2025-11-05',
    region: 'Hindu',
    deity: 'Lord Vishnu & Shiva',
    deityIcon: '🌕',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Krittika',
    month: 'Kartik',
    significance:
      'Holiest full moon — Lord Shiva killed demon Tripurasura. Celebrated as Dev Diwali in Varanasi with thousands of diyas on ghats.',
    whatToDo: [
      'Holy bath in Ganga / sacred river',
      'Light deepdaan (floating lamps)',
      'Visit Shiva or Vishnu temple',
      'Perform Satyanarayan katha',
    ],
    timing: 'Sandhya Kaal — 17:45 onwards (for deepdaan)',
    wish: 'May the divine light illuminate every corner of your life!',
    wishSub: 'Shubh Kartik Purnima 🌕',
    checklist: [
      { id: 1, text: 'Deep daan (lamps to float)', tag: '🪔' },
      { id: 2, text: 'Ghee & camphor', tag: '🕯️' },
      { id: 3, text: 'Satyanarayan prasad', tag: '🍬' },
      { id: 4, text: 'White flowers', tag: '🌼' },
    ],
  },
  {
    id: 'gurpurab-2025',
    name: 'Guru Nanak Jayanti',
    date: '2025-11-05',
    region: 'Sikh',
    deity: 'Guru Nanak Dev Ji',
    deityIcon: '🙏',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Krittika',
    month: 'Kartik',
    significance:
      '556th birth anniversary of Guru Nanak Dev Ji, founder of Sikhism. Celebrated with prabhat pheri, akhand path and langar.',
    whatToDo: [
      'Attend prabhat pheri (early morning procession)',
      'Visit Gurudwara for path',
      'Listen to kirtan',
      'Serve & eat langar',
      'Read Japji Sahib',
    ],
    timing: 'Amrit Vela — 03:00 to 06:00 (most blessed)',
    wish: "Waheguru Ji's blessings be with you always!",
    wishSub: 'Gurpurab Diyan Vadhaiyan 🙏',
    checklist: [
      { id: 1, text: 'Karah prasad (suji halwa)', tag: '🙏' },
      { id: 2, text: 'Langar dal & sabzi', tag: '🍽️' },
      { id: 3, text: 'White/blue clothes', tag: '👗' },
      { id: 4, text: 'Diyas & candles', tag: '🪔' },
    ],
  },
  {
    id: 'pongal-2026',
    name: 'Pongal / Makar Sankranti',
    date: '2026-01-14',
    region: 'Hindu',
    deity: 'Surya Bhagwan',
    deityIcon: '☀️',
    tithi: 'Saptami',
    paksha: 'Krishna',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Hasta',
    month: 'Pausha',
    significance:
      'Sun’s transit into Capricorn (Makar). Marks end of winter solstice and beginning of harvest season.',
    whatToDo: [
      'Holy dip at sunrise',
      'Make Pongal/khichdi from new harvest',
      'Donate til (sesame), gud (jaggery), woollen clothes',
      'Fly kites',
      'Offer arghya to Sun',
    ],
    timing: 'Punya Kaal — 07:15 to 12:30',
    wish: 'May the Sun bless you with warmth and abundance!',
    wishSub: 'Happy Makar Sankranti ☀️',
    checklist: [
      { id: 1, text: 'Til, gud, rice', tag: '🌾' },
      { id: 2, text: 'New clay pot (for Pongal)', tag: '🏺' },
      { id: 3, text: 'Sugarcane', tag: '🌿' },
      { id: 4, text: 'Kites & manjha', tag: '🪁' },
      { id: 5, text: 'Donation items', tag: '🎁' },
    ],
  },
  {
    id: 'mahashivratri-2026',
    name: 'Maha Shivratri',
    date: '2026-02-15',
    region: 'Hindu',
    deity: 'Lord Shiva',
    deityIcon: '🔱',
    tithi: 'Chaturdashi',
    paksha: 'Krishna',
    vara: 'Ravivara (Sunday)',
    nakshatra: 'Shravana',
    month: 'Phalguna',
    significance:
      'The great night of Shiva — celebrates the cosmic dance of Shiva (Tandava) and his marriage with Parvati.',
    whatToDo: [
      'Observe day-long fast (phalahar)',
      'Visit Shiva temple',
      'Offer bel patra, milk, water on Shivling',
      'Chant Om Namah Shivaya',
      'Stay awake all night for jagran',
    ],
    timing: '4 prahar puja — 18:00, 21:00, 00:00, 03:00',
    wish: 'Har Har Mahadev! May Lord Shiva bless you!',
    wishSub: 'Shubh Maha Shivratri 🔱',
    checklist: [
      { id: 1, text: 'Bel patra (3-leaf)', tag: '🍃' },
      { id: 2, text: 'Milk, dahi, ghee, honey', tag: '🥛' },
      { id: 3, text: 'Datura & dhatura flower', tag: '🌸' },
      { id: 4, text: 'Bhasma (sacred ash)', tag: '🪨' },
      { id: 5, text: 'Rudraksha mala', tag: '📿' },
      { id: 6, text: 'Phalahar (vrat food)', tag: '🍎' },
    ],
  },
  {
    id: 'holi-2026',
    name: 'Holi (Rangwali)',
    date: '2026-03-14',
    region: 'Hindu',
    deity: 'Krishna & Radha',
    deityIcon: '🎨',
    tithi: 'Pratipada',
    paksha: 'Krishna',
    vara: 'Shanivara (Saturday)',
    nakshatra: 'Uttara Phalguni',
    month: 'Chaitra',
    significance:
      'Festival of colours celebrating victory of good over evil (Prahlad & Holika story). Day after Holika Dahan.',
    whatToDo: [
      'Holika Dahan on previous evening',
      'Apply gulal to family & friends',
      'Sing & dance to Holi songs',
      'Eat gujiya, thandai, dahi vada',
    ],
    timing: 'Holika Dahan — Pradosh Kaal previous day; Color play — morning',
    wish: 'May your life be filled with vibrant colours of joy!',
    wishSub: 'Happy Holi 🎨',
    checklist: [
      { id: 1, text: 'Herbal gulal & rang', tag: '🎨' },
      { id: 2, text: 'Pichkari (water gun)', tag: '💦' },
      { id: 3, text: 'Thandai ingredients', tag: '🥛' },
      { id: 4, text: 'Gujiya & dahi bhalla', tag: '🍬' },
      { id: 5, text: 'Old white clothes', tag: '👕' },
      { id: 6, text: 'Holika dahan wood', tag: '🔥' },
    ],
  },
  {
    id: 'ramnavami-2026',
    name: 'Rama Navami',
    date: '2026-03-26',
    region: 'Hindu',
    deity: 'Lord Rama',
    deityIcon: '🏹',
    tithi: 'Navami',
    paksha: 'Shukla',
    vara: 'Guruvara (Thursday)',
    nakshatra: 'Punarvasu',
    month: 'Chaitra',
    significance:
      'Birth of Lord Rama, the seventh avatar of Vishnu. Climax of Chaitra Navratri.',
    whatToDo: [
      'Recite Ramayan / Sundar Kand',
      'Fast and offer prasad at noon',
      'Visit Ram temple',
      'Sing bhajans & kirtan',
    ],
    timing: 'Madhyahna — 11:00 to 13:30 (Lord Rama’s birth time)',
    wish: 'Jai Shri Ram! May Lord Rama’s grace be upon you!',
    wishSub: 'Shubh Ram Navami 🏹',
    checklist: [
      { id: 1, text: 'Ram darbar photo / idol', tag: '🙏' },
      { id: 2, text: 'Tulsi & yellow flowers', tag: '🌼' },
      { id: 3, text: 'Panchamrit', tag: '🥛' },
      { id: 4, text: 'Sundar Kand book', tag: '📖' },
      { id: 5, text: 'Kheer / panjiri prasad', tag: '🍬' },
    ],
  },
  {
    id: 'eid-2026',
    name: 'Eid ul-Fitr',
    date: '2026-03-30',
    region: 'Muslim',
    deity: 'Allah',
    deityIcon: '🌙',
    tithi: 'Shawwal 1',
    vara: 'Somavara (Monday)',
    nakshatra: '—',
    month: 'Shawwal (Hijri)',
    significance:
      'Marks the end of Ramadan, the holy month of fasting. A celebration of gratitude and charity.',
    whatToDo: [
      'Pay Zakat al-Fitr before Eid prayer',
      'Eid namaz at masjid',
      'Wear new clothes',
      'Greet "Eid Mubarak"',
      'Visit family, distribute Eidi',
    ],
    timing: 'Eid namaz — after sunrise (around 06:30)',
    wish: 'Eid Mubarak! May Allah bless you with happiness!',
    wishSub: 'Eid Mubarak ☪️',
    checklist: [
      { id: 1, text: 'New eid clothes', tag: '👗' },
      { id: 2, text: 'Sheer khurma & sevaiyan', tag: '🍬' },
      { id: 3, text: 'Eidi envelopes', tag: '💝' },
      { id: 4, text: 'Itar (perfume)', tag: '🌹' },
      { id: 5, text: 'Dates & dry fruits', tag: '🌴' },
      { id: 6, text: 'Zakat amount', tag: '🤲' },
    ],
  },
  {
    id: 'easter-2026',
    name: 'Easter Sunday',
    date: '2026-04-05',
    region: 'Christian',
    deity: 'Jesus Christ',
    deityIcon: '✝️',
    tithi: '—',
    vara: 'Ravivara (Sunday)',
    nakshatra: '—',
    month: 'April',
    significance:
      'Resurrection of Jesus Christ from the dead. Most important Christian festival celebrating victory of life over death.',
    whatToDo: [
      'Attend Easter Sunday mass',
      'Light Paschal candle',
      'Easter egg hunt with children',
      'Family feast',
      'Greet "He is Risen!"',
    ],
    timing: 'Sunrise service — 05:30 to 07:00',
    wish: 'He is Risen! May joy and hope fill your heart!',
    wishSub: 'Happy Easter 🐣',
    checklist: [
      { id: 1, text: 'Easter eggs & chocolates', tag: '🥚' },
      { id: 2, text: 'Easter basket', tag: '🎁' },
      { id: 3, text: 'Hot cross buns', tag: '🍞' },
      { id: 4, text: 'Paschal candles', tag: '🕯️' },
      { id: 5, text: 'New spring clothes', tag: '👗' },
    ],
  },
  {
    id: 'baisakhi-2026',
    name: 'Baisakhi',
    date: '2026-04-14',
    region: 'Sikh',
    deity: 'Guru Gobind Singh & Khalsa',
    deityIcon: '🌾',
    tithi: 'Pratipada',
    paksha: 'Shukla',
    vara: 'Mangalvara (Tuesday)',
    nakshatra: 'Ashwini',
    month: 'Vaisakha',
    significance:
      'Birth of the Khalsa Panth in 1699 by Guru Gobind Singh Ji. Also celebrates spring harvest.',
    whatToDo: [
      'Visit Gurudwara at amrit vela',
      'Listen to Guru Granth Sahib path',
      'Bhangra/Giddha celebration',
      'Wear traditional Punjabi attire',
      'Serve langar',
    ],
    timing: 'Amrit Vela — 03:00 to 06:00',
    wish: 'Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh!',
    wishSub: 'Happy Baisakhi 🌾',
    checklist: [
      { id: 1, text: 'Colourful turbans & dupatte', tag: '👗' },
      { id: 2, text: 'Karah prasad', tag: '🙏' },
      { id: 3, text: 'Langar ingredients', tag: '🍽️' },
      { id: 4, text: 'Dholki / dhol', tag: '🪘' },
    ],
  },
  {
    id: 'akshaya-tritiya-2026',
    name: 'Akshaya Tritiya',
    date: '2026-04-20',
    region: 'Hindu',
    deity: 'Lakshmi & Vishnu',
    deityIcon: '💎',
    tithi: 'Tritiya',
    paksha: 'Shukla',
    vara: 'Somavara (Monday)',
    nakshatra: 'Rohini',
    month: 'Vaisakha',
    significance:
      'One of 4 most auspicious days. "Akshaya" means imperishable — any good deed multiplies infinitely. Best day to buy gold.',
    whatToDo: [
      'Buy gold, silver, or property',
      'Donate to needy (annadaan)',
      'Lakshmi-Narayan puja',
      'Recite Vishnu Sahasranama',
      'Begin new ventures',
    ],
    timing: 'Whole day auspicious; best 05:45 to 12:18',
    wish: 'May this Akshaya Tritiya bring eternal prosperity!',
    wishSub: 'Shubh Akshaya Tritiya 💎',
    checklist: [
      { id: 1, text: 'Gold/silver coin', tag: '🪙' },
      { id: 2, text: 'Tulsi leaves', tag: '🌿' },
      { id: 3, text: 'Yellow flowers', tag: '🌼' },
      { id: 4, text: 'Donation items (food/clothes)', tag: '🎁' },
    ],
  },
  {
    id: 'eid-al-adha-2026',
    name: 'Eid ul-Adha (Bakrid)',
    date: '2026-06-06',
    region: 'Muslim',
    deity: 'Allah',
    deityIcon: '🐑',
    tithi: 'Dhul-Hijjah 10',
    vara: 'Shanivara (Saturday)',
    nakshatra: '—',
    month: 'Dhul-Hijjah (Hijri)',
    significance:
      'Festival of Sacrifice — commemorates Prophet Ibrahim’s willingness to sacrifice his son for Allah. Climax of Hajj pilgrimage.',
    whatToDo: [
      'Eid namaz at masjid',
      'Qurbani (animal sacrifice)',
      'Distribute meat in 3 parts (family/friends/poor)',
      'Visit relatives',
      'Wear new clothes',
    ],
    timing: 'Eid namaz — after sunrise (around 06:00)',
    wish: 'Eid ul-Adha Mubarak! May your sacrifice be accepted!',
    wishSub: 'Eid Mubarak ☪️',
    checklist: [
      { id: 1, text: 'New clothes', tag: '👗' },
      { id: 2, text: 'Qurbani arrangements', tag: '🍖' },
      { id: 3, text: 'Sevaiyan & halwa', tag: '🍬' },
      { id: 4, text: 'Gifts for children', tag: '🎁' },
    ],
  },
  {
    id: 'guru-purnima-2026',
    name: 'Guru Purnima',
    date: '2026-07-29',
    region: 'Hindu',
    deity: 'Guru / Vyasa',
    deityIcon: '📖',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Uttara Ashadha',
    month: 'Ashadha',
    significance:
      'Honors all spiritual gurus and Maharishi Vyasa, who composed the Vedas. Day to express gratitude to teachers.',
    whatToDo: [
      'Take blessings from your guru',
      'Read scriptures (Gita / Vedas)',
      'Practice extra meditation',
      'Donate to ashram or seva',
      'Recite Guru mantra 108 times',
    ],
    timing: 'Brahma Muhurta — 04:15 to 05:45',
    wish: 'Pranam to all gurus who light our path!',
    wishSub: 'Guru Purnima Shubhkamna 📖',
    checklist: [
      { id: 1, text: 'Guru padukas / photo', tag: '🙏' },
      { id: 2, text: 'White flowers', tag: '🌼' },
      { id: 3, text: 'Sweets for offering', tag: '🍬' },
      { id: 4, text: 'Bhagavad Gita / Vedas', tag: '📖' },
    ],
  },
  {
    id: 'janmashtami-2026',
    name: 'Krishna Janmashtami',
    date: '2026-09-04',
    region: 'Hindu',
    deity: 'Lord Krishna',
    deityIcon: '🪈',
    tithi: 'Ashtami',
    paksha: 'Krishna',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Rohini',
    month: 'Bhadrapada',
    significance:
      'Birth of Lord Krishna, the 8th avatar of Vishnu. Born at midnight in Mathura prison to Devaki and Vasudeva.',
    whatToDo: [
      'Day-long fast (vrat)',
      'Decorate Krishna jhanki / cradle',
      'Sing bhajans till midnight',
      'Break fast with Panjiri prasad after midnight aarti',
      'Visit Krishna temple',
    ],
    timing: 'Nishita Kaal — 23:42 to 00:25 (midnight, Krishna’s birth)',
    wish: 'Jai Shri Krishna! May Lord Krishna fill your life with love!',
    wishSub: 'Shubh Janmashtami 🪈',
    checklist: [
      { id: 1, text: 'Cradle (jhula) for Ladoo Gopal', tag: '🛏️' },
      { id: 2, text: 'Butter, mishri, makhan', tag: '🧈' },
      { id: 3, text: 'Yellow & peacock decor', tag: '🦚' },
      { id: 4, text: 'Tulsi leaves', tag: '🌿' },
      { id: 5, text: 'Panchamrit & panjiri', tag: '🍬' },
      { id: 6, text: 'Flute (bansuri)', tag: '🪈' },
    ],
  },
  {
    id: 'ganesh-chaturthi-2026',
    name: 'Ganesh Chaturthi',
    date: '2026-09-15',
    region: 'Hindu',
    deity: 'Lord Ganesha',
    deityIcon: '🐘',
    tithi: 'Chaturthi',
    paksha: 'Shukla',
    vara: 'Mangalvara (Tuesday)',
    nakshatra: 'Hasta',
    month: 'Bhadrapada',
    significance:
      'Birth of Lord Ganesha, the remover of obstacles. 10-day festival ending with Anant Chaturdashi visarjan.',
    whatToDo: [
      'Sthapana (installation) at sunrise',
      'Daily aarti morning & evening',
      'Offer 21 modaks',
      'Avoid sighting moon (Mithya Dosha)',
      'Visarjan on Anant Chaturdashi (after 10 days)',
    ],
    timing: 'Madhyahna — 11:01 to 13:28 (best for sthapana)',
    wish: 'Ganpati Bappa Morya! May Ganesha remove all obstacles!',
    wishSub: 'Shubh Ganesh Chaturthi 🐘',
    checklist: [
      { id: 1, text: 'Eco-clay Ganesha idol', tag: '🐘' },
      { id: 2, text: 'Modak (21 pieces)', tag: '🍬' },
      { id: 3, text: 'Durva grass (21 strands)', tag: '🌿' },
      { id: 4, text: 'Red flowers (jaswand)', tag: '🌺' },
      { id: 5, text: 'Panchamrit & coconut', tag: '🥥' },
      { id: 6, text: 'Dhup, deep, kapur', tag: '🪔' },
    ],
  },
  {
    id: 'christmas-2025',
    name: 'Christmas',
    date: '2025-12-25',
    region: 'Christian',
    deity: 'Jesus Christ',
    deityIcon: '🎄',
    tithi: '—',
    vara: 'Guruvara (Thursday)',
    nakshatra: '—',
    month: 'December',
    significance:
      'Birth of Jesus Christ, the Son of God. Celebrated worldwide as a festival of peace, love and giving.',
    whatToDo: [
      'Attend midnight mass',
      'Decorate Christmas tree',
      'Set up nativity scene',
      'Exchange gifts',
      'Sing carols & enjoy feast',
    ],
    timing: 'Midnight mass — 23:00 to 00:30',
    wish: 'Wishing you a blessed Christmas filled with joy & peace!',
    wishSub: 'Merry Christmas 🎄',
    checklist: [
      { id: 1, text: 'Christmas tree & ornaments', tag: '🎄' },
      { id: 2, text: 'Nativity scene set', tag: '⭐' },
      { id: 3, text: 'Plum cake & cookies', tag: '🎂' },
      { id: 4, text: 'Gift wrapping supplies', tag: '🎁' },
      { id: 5, text: 'Candles & fairy lights', tag: '🕯️' },
      { id: 6, text: 'Stockings & santa hat', tag: '🎅' },
    ],
  },
];

// More festivals from Drik Panchang Hindu calendar 2025-26
PANCHANG_FESTIVALS.push(
  {
    id: 'vasant-panchami-2026',
    name: 'Vasant Panchami (Saraswati Puja)',
    date: '2026-01-23',
    region: 'Hindu',
    deity: 'Goddess Saraswati',
    deityIcon: '📚',
    tithi: 'Panchami',
    paksha: 'Shukla',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Uttara Bhadrapada',
    month: 'Magha',
    significance:
      'Worship of Goddess Saraswati, the deity of knowledge, music and arts. Marks the arrival of spring (vasant ritu). First day for children to begin learning (Vidyarambh).',
    whatToDo: [
      'Wear yellow clothes',
      'Place books, instruments before Saraswati',
      'Offer yellow flowers and kesar kheer',
      'Vidyarambh ceremony for kids',
      'Avoid cutting trees on this day',
    ],
    timing: 'Madhyahna — 11:30 to 13:00',
    poojaTimings: [
      { label: 'Saraswati Puja Muhurat', from: '11:30', to: '13:00' },
    ],
    fromTime: 'Sunrise',
    toTime: 'Sunset',
    wish: 'May Maa Saraswati bless you with wisdom and creativity!',
    wishSub: 'Shubh Vasant Panchami 📚',
    checklist: [
      { id: 1, text: 'Yellow flowers (mustard)', tag: '🌼' },
      { id: 2, text: 'Saraswati idol/photo', tag: '🙏' },
      { id: 3, text: 'Kesar kheer ingredients', tag: '🥛' },
      { id: 4, text: 'Yellow clothes', tag: '👗' },
      { id: 5, text: 'Books / pen / instruments', tag: '📚' },
    ],
  },
  {
    id: 'mauni-amavasya-2026',
    name: 'Mauni Amavasya',
    date: '2026-01-19',
    region: 'Hindu',
    deity: 'Lord Vishnu',
    deityIcon: '🌑',
    tithi: 'Amavasya',
    paksha: 'Krishna',
    vara: 'Somavara (Monday)',
    nakshatra: 'Uttara Ashadha',
    month: 'Magha',
    significance:
      'Most auspicious Amavasya for silent meditation (mauna vrata). Holy bath at Sangam during Magh Mela liberates from sins.',
    whatToDo: [
      'Observe silence (mauna)',
      'Holy dip in Ganga at sunrise',
      'Donate til, gud, blankets',
      'Tarpan for ancestors',
      'Avoid speaking till noon',
    ],
    timing: 'Brahma Muhurat — 04:30 to 06:00 (best for snan)',
    fromTime: '04:30',
    toTime: 'Sunset',
    wish: 'May silence bring inner peace!',
    wishSub: 'Mauni Amavasya 🌑',
    checklist: [
      { id: 1, text: 'Til, gud, blankets', tag: '🌾' },
      { id: 2, text: 'Pitru tarpan items', tag: '🪔' },
      { id: 3, text: 'White clothes', tag: '👗' },
    ],
  },
  {
    id: 'thaipusam-2026',
    name: 'Thaipusam',
    date: '2026-02-01',
    region: 'Hindu',
    deity: 'Lord Murugan (Kartikeya)',
    deityIcon: '🦚',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Ravivara (Sunday)',
    nakshatra: 'Pushya',
    month: 'Magha',
    significance:
      'Lord Murugan defeated demon Soorapadman on this day. Devotees carry kavadi as penance and offering.',
    whatToDo: [
      'Visit Murugan temple',
      'Carry pal kavadi (milk pot)',
      'Apply vibhuti and kumkum',
      'Recite Skanda Sashti Kavasam',
      'Observe fast',
    ],
    timing: 'Whole day; Pradosh kaal (16:30 to 19:00) most auspicious',
    fromTime: 'Sunrise',
    toTime: 'Sunset',
    wish: 'Vetri Vel Muruganukku Arohara!',
    wishSub: 'Thaipusam Vazhthukkal 🦚',
    checklist: [
      { id: 1, text: 'Milk for kavadi', tag: '🥛' },
      { id: 2, text: 'Vibhuti & kumkum', tag: '🔴' },
      { id: 3, text: 'Yellow/orange clothes', tag: '👗' },
    ],
  },
  {
    id: 'ratha-saptami-2026',
    name: 'Ratha Saptami (Surya Jayanti)',
    date: '2026-02-04',
    region: 'Hindu',
    deity: 'Surya Bhagwan',
    deityIcon: '☀️',
    tithi: 'Saptami',
    paksha: 'Shukla',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Revati',
    month: 'Magha',
    significance:
      'Birth of Sun God; Surya begins his northward journey. Bath with arka leaves removes diseases.',
    whatToDo: [
      'Bath with 7 arka (calotropis) leaves',
      'Offer arghya to Surya at sunrise',
      'Recite Aditya Hridaya Stotra',
      'Donate red items',
    ],
    timing: 'Sunrise — 06:30 to 07:30',
    fromTime: 'Sunrise (06:30)',
    toTime: '08:30',
    wish: 'May Surya Dev bless you with health and energy!',
    wishSub: 'Ratha Saptami Shubhkamna ☀️',
    checklist: [
      { id: 1, text: 'Arka leaves (7)', tag: '🍃' },
      { id: 2, text: 'Red flowers', tag: '🌹' },
      { id: 3, text: 'Copper pot for arghya', tag: '🏺' },
    ],
  },
  {
    id: 'holashtak-2026',
    name: 'Holashtak begins',
    date: '2026-03-07',
    region: 'Hindu',
    deity: '—',
    deityIcon: '🚫',
    tithi: 'Ashtami',
    paksha: 'Shukla',
    vara: 'Shanivara (Saturday)',
    nakshatra: 'Punarvasu',
    month: 'Phalguna',
    significance:
      '8-day inauspicious period before Holi when no auspicious events (marriage, mundan, griha pravesh) are performed.',
    whatToDo: [
      'Avoid new ventures',
      'No marriage / griha pravesh',
      'Increase chanting and seva',
      'Give donations',
    ],
    timing: 'Begins from Phalgun Shukla Ashtami till Phalgun Purnima',
    wish: 'May this period bring inner reflection',
    wishSub: 'Holashtak 🚫',
    checklist: [],
  },
  {
    id: 'holika-dahan-2026',
    name: 'Holika Dahan',
    date: '2026-03-13',
    region: 'Hindu',
    deity: 'Vishnu (Prahlad story)',
    deityIcon: '🔥',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Purva Phalguni',
    month: 'Phalguna',
    significance:
      'Burning of Holika who tried to kill Bhakta Prahlad. Symbolizes burning away of ego and negativity.',
    whatToDo: [
      'Light Holika bonfire after sunset',
      'Circumambulate the fire',
      'Offer coconut, gulal, raw mango',
      'Chant Narsimha mantra',
    ],
    timing: 'Pradosh Kaal — 18:30 to 20:50',
    poojaTimings: [{ label: 'Holika Dahan Muhurat', from: '18:30', to: '20:50' }],
    fromTime: '18:30',
    toTime: '20:50',
    wish: 'May Holika Dahan burn all evil within!',
    wishSub: 'Shubh Holika Dahan 🔥',
    checklist: [
      { id: 1, text: 'Wood & cow dung cakes', tag: '🪵' },
      { id: 2, text: 'Coconut & raw mango', tag: '🥥' },
      { id: 3, text: 'Gulal (red colour)', tag: '🎨' },
      { id: 4, text: 'Roli, mauli, akshat', tag: '🔴' },
    ],
  },
  {
    id: 'gudi-padwa-2026',
    name: 'Gudi Padwa / Ugadi',
    date: '2026-03-19',
    region: 'Hindu',
    deity: 'Brahma',
    deityIcon: '🚩',
    tithi: 'Pratipada',
    paksha: 'Shukla',
    vara: 'Guruvara (Thursday)',
    nakshatra: 'Revati',
    month: 'Chaitra',
    significance:
      'Hindu New Year (Vikram Samvat). Lord Brahma created the universe on this day. Marks beginning of spring harvest.',
    whatToDo: [
      'Hoist Gudi (flag) outside home',
      'Eat neem leaves with jaggery',
      'Make ugadi pachadi (6 tastes)',
      'Read panchang for new year',
      'Begin new ventures',
    ],
    timing: 'Sunrise — 06:30 onwards (most auspicious all day)',
    fromTime: 'Sunrise',
    toTime: 'Sunset',
    wish: 'New year blessings to you and your family!',
    wishSub: 'Gudi Padwa / Ugadi Shubhkamna 🚩',
    checklist: [
      { id: 1, text: 'Bamboo stick & saffron cloth', tag: '🚩' },
      { id: 2, text: 'Neem leaves & jaggery', tag: '🍃' },
      { id: 3, text: 'New panchang book', tag: '📖' },
      { id: 4, text: 'Kalash & coconut', tag: '🥥' },
      { id: 5, text: 'Mango leaves toran', tag: '🌿' },
    ],
  },
  {
    id: 'chaitra-navratri-day1-2026',
    name: 'Chaitra Navratri Day 1',
    date: '2026-03-19',
    region: 'Hindu',
    deity: 'Maa Shailaputri',
    deityIcon: '🌸',
    tithi: 'Pratipada',
    paksha: 'Shukla',
    vara: 'Guruvara (Thursday)',
    nakshatra: 'Revati',
    month: 'Chaitra',
    significance:
      'Beginning of Chaitra Navratri — 9-day celebration of Goddess Durga in spring. Worship of Maa Shailaputri.',
    whatToDo: [
      'Ghatasthapana at sunrise',
      'Begin 9-day fast',
      'Recite Durga Saptashati daily',
      'Offer ghee to Devi',
    ],
    timing: 'Pratahkaal — 06:00 to 09:00',
    poojaTimings: [{ label: 'Ghatasthapana Muhurat', from: '06:00', to: '09:00' }],
    fromTime: '06:00',
    toTime: '09:00',
    wish: 'Jai Maa Durga! 9 days of devotion begin!',
    wishSub: 'Chaitra Navratri Shubhkamna 🌸',
    checklist: [
      { id: 1, text: 'Kalash & coconut', tag: '🥥' },
      { id: 2, text: 'Red cloth', tag: '🧵' },
      { id: 3, text: 'Akhand jyoti & oil', tag: '🪔' },
      { id: 4, text: 'Marigold flowers', tag: '🌼' },
    ],
  },
  {
    id: 'hanuman-jayanti-2026',
    name: 'Hanuman Jayanti',
    date: '2026-04-03',
    region: 'Hindu',
    deity: 'Lord Hanuman',
    deityIcon: '🐒',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Chitra',
    month: 'Chaitra',
    significance:
      'Birth of Lord Hanuman, the embodiment of strength, devotion and selfless service to Lord Rama.',
    whatToDo: [
      'Visit Hanuman temple',
      'Recite Hanuman Chalisa 11 times',
      'Offer sindoor and chola',
      'Read Sundar Kand',
      'Observe fast',
    ],
    timing: 'Whole day; Brahma Muhurat (04:30) for chalisa',
    poojaTimings: [{ label: 'Sundar Kand Path', from: '06:00', to: '08:30' }],
    fromTime: 'Sunrise',
    toTime: 'Sunset',
    wish: 'Jai Bajrangbali! May Hanuman ji bless you!',
    wishSub: 'Hanuman Jayanti Shubhkamna 🐒',
    checklist: [
      { id: 1, text: 'Sindoor & chameli oil', tag: '🔴' },
      { id: 2, text: 'Boondi laddoo', tag: '🍬' },
      { id: 3, text: 'Hanuman Chalisa book', tag: '📖' },
      { id: 4, text: 'Banana / chana for prasad', tag: '🍌' },
    ],
  },
  {
    id: 'buddha-purnima-2026',
    name: 'Buddha Purnima (Vesak)',
    date: '2026-05-01',
    region: 'Hindu',
    deity: 'Lord Buddha',
    deityIcon: '☸️',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Vishakha',
    month: 'Vaisakha',
    significance:
      "Lord Buddha's birth, enlightenment and mahaparinirvana — all on the same day (Vesak). Most sacred day for Buddhists.",
    whatToDo: [
      'Visit Buddhist monastery / temple',
      'Meditate for peace',
      'Light butter lamps',
      'Donate food (annadaan)',
      'Avoid violence and meat',
    ],
    timing: 'Brahma Muhurat — 04:00 to 06:00 (meditation)',
    fromTime: '04:00',
    toTime: 'Sunset',
    wish: 'Buddham Sharanam Gacchami!',
    wishSub: 'Buddha Purnima Shubhkamna ☸️',
    checklist: [
      { id: 1, text: 'Butter lamps', tag: '🪔' },
      { id: 2, text: 'White flowers', tag: '🌼' },
      { id: 3, text: 'Food for donation', tag: '🍱' },
      { id: 4, text: 'Buddha photo / idol', tag: '☸️' },
    ],
  },
  {
    id: 'vat-savitri-2026',
    name: 'Vat Savitri Vrat',
    date: '2026-05-16',
    region: 'Hindu',
    deity: 'Goddess Savitri & Banyan tree',
    deityIcon: '🌳',
    tithi: 'Amavasya',
    paksha: 'Krishna',
    vara: 'Shanivara (Saturday)',
    nakshatra: 'Krittika',
    month: 'Jyeshtha',
    significance:
      'Married women fast for the long life of their husbands. Story of Savitri who brought back her husband Satyavan from Yamraj.',
    whatToDo: [
      'Tie 7 threads around banyan tree',
      'Listen to Savitri-Satyavan katha',
      'Offer water, fruits, sweets to tree',
      'Observe nirjala vrat',
      'Apply mehndi and dress as bride',
    ],
    timing: 'Sunrise to moonrise (full day fast)',
    vrataInfo: 'Nirjala vrat (without water) full day',
    fromTime: 'Sunrise',
    toTime: 'Moonrise',
    wish: 'May the bond of marriage grow stronger!',
    wishSub: 'Vat Savitri Vrat Shubhkamna 🌳',
    checklist: [
      { id: 1, text: '7 cotton threads', tag: '🧵' },
      { id: 2, text: 'Bamboo basket (daliya)', tag: '🧺' },
      { id: 3, text: 'Mehndi & shringar', tag: '💄' },
      { id: 4, text: 'Fruits & sweets', tag: '🍬' },
      { id: 5, text: 'Red bridal saree', tag: '👗' },
    ],
  },
  {
    id: 'ganga-dussehra-2026',
    name: 'Ganga Dussehra',
    date: '2026-06-05',
    region: 'Hindu',
    deity: 'Maa Ganga',
    deityIcon: '🌊',
    tithi: 'Dashami',
    paksha: 'Shukla',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Hasta',
    month: 'Jyeshtha',
    significance:
      'Descent of Ganga from heaven to earth. Holy bath in Ganga on this day frees one from 10 sins (dasha-papa).',
    whatToDo: [
      'Holy dip in Ganga or sacred river',
      'Recite Ganga Stotra',
      'Donate til, dahi, ghee',
      'Light 10 diyas at Ganga ghat',
    ],
    timing: 'Pratahkaal — 04:30 to 08:00 (best for snan)',
    fromTime: '04:30',
    toTime: 'Sunset',
    wish: 'Har Har Gange! May Ganga Maa cleanse all sins!',
    wishSub: 'Ganga Dussehra Shubhkamna 🌊',
    checklist: [
      { id: 1, text: 'Til (sesame) & honey', tag: '🌾' },
      { id: 2, text: '10 diyas for ghat', tag: '🪔' },
      { id: 3, text: 'White clothes', tag: '👗' },
    ],
  },
  {
    id: 'nirjala-ekadashi-2026',
    name: 'Nirjala Ekadashi',
    date: '2026-06-11',
    region: 'Hindu',
    deity: 'Lord Vishnu',
    deityIcon: '🪷',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Guruvara (Thursday)',
    nakshatra: 'Anuradha',
    month: 'Jyeshtha',
    significance:
      'Most difficult Ekadashi — fast without even water for 24 hours. Equivalent merit to all 24 Ekadashis combined.',
    whatToDo: [
      'Wake at Brahma Muhurat',
      'Observe nirjala (waterless) fast',
      'Donate water-pots, fans, umbrellas',
      'Recite Vishnu Sahasranama',
      'Sleep on the floor',
    ],
    timing: 'Sunrise to next day sunrise',
    vrataInfo: 'Nirjala (waterless) for 24 hours — most difficult fast',
    fromTime: 'Sunrise (Day 1)',
    toTime: 'Sunrise (Day 2)',
    wish: 'May Lord Vishnu bless your devotion!',
    wishSub: 'Nirjala Ekadashi Shubhkamna 🪷',
    checklist: [
      { id: 1, text: 'Earthen pots (matkis)', tag: '🏺' },
      { id: 2, text: 'Hand fans (pankha)', tag: '🪭' },
      { id: 3, text: 'Umbrella for daan', tag: '☂️' },
      { id: 4, text: 'Tulsi & yellow flowers', tag: '🌿' },
    ],
  },
  {
    id: 'rath-yatra-2026',
    name: 'Jagannath Rath Yatra',
    date: '2026-07-17',
    region: 'Hindu',
    deity: 'Lord Jagannath',
    deityIcon: '🛕',
    tithi: 'Dwitiya',
    paksha: 'Shukla',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Pushya',
    month: 'Ashadha',
    significance:
      "Lord Jagannath, Balabhadra and Subhadra travel from Puri's Jagannath temple to Gundicha temple in chariots. Most famous yatra in India.",
    whatToDo: [
      'Visit Puri Jagannath temple',
      'Pull the chariot ropes (highest punya)',
      'Offer khichdi (Mahaprasad)',
      'Listen to Jagannath ashtakam',
    ],
    timing: 'Yatra begins ~16:00 from temple',
    fromTime: '16:00',
    toTime: '20:00',
    wish: 'Jai Jagannath! May Lord pull you out of all sufferings!',
    wishSub: 'Rath Yatra Shubhkamna 🛕',
    checklist: [
      { id: 1, text: 'Yellow & red flowers', tag: '🌺' },
      { id: 2, text: 'Khichdi ingredients', tag: '🍱' },
      { id: 3, text: 'Tulsi & camphor', tag: '🌿' },
    ],
  },
  {
    id: 'hariyali-teej-2026',
    name: 'Hariyali Teej',
    date: '2026-08-16',
    region: 'Hindu',
    deity: 'Maa Parvati & Shiva',
    deityIcon: '🌿',
    tithi: 'Tritiya',
    paksha: 'Shukla',
    vara: 'Ravivara (Sunday)',
    nakshatra: 'Hasta',
    month: 'Shravan',
    significance:
      "Reunion of Maa Parvati with Lord Shiva after 108 births of penance. Married women pray for husband's well-being and unmarried for good husband.",
    whatToDo: [
      'Wear green saree and bangles',
      'Apply mehndi',
      'Swing on tree (jhoola)',
      'Listen to Teej katha',
      'Offer fruits to Parvati',
    ],
    timing: 'Sunrise to moonrise (full day fast)',
    vrataInfo: 'Phalahar vrat (only fruits)',
    fromTime: 'Sunrise',
    toTime: 'Moonrise',
    wish: 'May Parvati Maa shower love and happiness!',
    wishSub: 'Hariyali Teej Mubarak 🌿',
    checklist: [
      { id: 1, text: 'Green saree & bangles', tag: '👗' },
      { id: 2, text: 'Mehndi cone', tag: '💚' },
      { id: 3, text: 'Coconut & sweets', tag: '🥥' },
      { id: 4, text: 'Sindoor', tag: '🔴' },
    ],
  },
  {
    id: 'nag-panchami-2026',
    name: 'Nag Panchami',
    date: '2026-08-18',
    region: 'Hindu',
    deity: 'Nag Devta (Serpent)',
    deityIcon: '🐍',
    tithi: 'Panchami',
    paksha: 'Shukla',
    vara: 'Mangalvara (Tuesday)',
    nakshatra: 'Chitra',
    month: 'Shravan',
    significance:
      'Worship of serpent gods (Vasuki, Sheshnag, Takshak). Removes Kal Sarp dosha.',
    whatToDo: [
      'Offer milk to snake idol/painting',
      'Recite Nag Stotra',
      'Avoid digging earth or cooking on tava',
      'Donate til to Brahmin',
    ],
    timing: 'Madhyahna — 11:30 to 13:00',
    fromTime: 'Sunrise',
    toTime: 'Sunset',
    wish: 'May Nag Devta protect you from all harm!',
    wishSub: 'Nag Panchami Shubhkamna 🐍',
    checklist: [
      { id: 1, text: 'Milk for offering', tag: '🥛' },
      { id: 2, text: 'Lotus flowers', tag: '🪷' },
      { id: 3, text: 'Kheer & dahi', tag: '🍚' },
    ],
  },
  {
    id: 'raksha-bandhan-2026',
    name: 'Raksha Bandhan',
    date: '2026-08-28',
    region: 'Hindu',
    deity: 'Brother-Sister bond',
    deityIcon: '🪢',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Shravana',
    month: 'Shravan',
    significance:
      "Sister ties rakhi on brother's wrist; brother takes vow of protection. Origin in Indra-Sachi story.",
    whatToDo: [
      'Tie rakhi after morning bath',
      'Apply tilak with roli & rice',
      'Sister offers sweets',
      'Brother gives gift / shagun',
      'Take blessings of elders',
    ],
    timing: 'Avoid Bhadra Kaal; check muhurat (typically 11:00 to 14:00)',
    poojaTimings: [{ label: 'Aparahna Muhurat', from: '13:30', to: '16:30' }],
    fromTime: '13:30',
    toTime: '16:30',
    wish: 'May the bond of love grow stronger!',
    wishSub: 'Happy Raksha Bandhan 🪢',
    checklist: [
      { id: 1, text: 'Rakhi (sister buys)', tag: '🪢' },
      { id: 2, text: 'Roli, rice, diya', tag: '🔴' },
      { id: 3, text: 'Sweets (kaju, ladoo)', tag: '🍬' },
      { id: 4, text: 'Gift for sister', tag: '🎁' },
      { id: 5, text: 'New clothes', tag: '👗' },
    ],
  },
  {
    id: 'anant-chaturdashi-2026',
    name: 'Anant Chaturdashi (Ganesh Visarjan)',
    date: '2026-09-25',
    region: 'Hindu',
    deity: 'Lord Vishnu (Anant) & Ganesha',
    deityIcon: '🌊',
    tithi: 'Chaturdashi',
    paksha: 'Shukla',
    vara: 'Shukravara (Friday)',
    nakshatra: 'Uttara Ashadha',
    month: 'Bhadrapada',
    significance:
      'Final day of Ganesh Utsav with grand visarjan. Also worship of Anant (Vishnu) — tying 14-knot thread.',
    whatToDo: [
      'Final aarti of Ganesha',
      'Visarjan procession to water body',
      'Tie 14-knot anant thread',
      'Sing "Ganpati Bappa Morya"',
    ],
    timing: 'Pratahkaal aarti; Visarjan in afternoon',
    poojaTimings: [{ label: 'Anant Sutra Pujan', from: '08:00', to: '11:00' }],
    fromTime: 'Sunrise',
    toTime: 'Sunset',
    wish: 'Ganpati Bappa Morya! Pudhchya varshi lavkar ya!',
    wishSub: 'Anant Chaturdashi 🌊',
    checklist: [
      { id: 1, text: 'Anant sutra (14 knots)', tag: '🪢' },
      { id: 2, text: 'Modak for visarjan', tag: '🍬' },
      { id: 3, text: 'Garland & flowers', tag: '🌺' },
      { id: 4, text: 'Coconut for visarjan', tag: '🥥' },
    ],
  },
  {
    id: 'pitru-paksha-2026',
    name: 'Pitru Paksha begins',
    date: '2026-09-26',
    region: 'Hindu',
    deity: 'Pitru (ancestors)',
    deityIcon: '🕯️',
    tithi: 'Pratipada',
    paksha: 'Krishna',
    vara: 'Shanivara (Saturday)',
    nakshatra: 'Shravana',
    month: 'Ashwin',
    significance:
      '16-day period to honor and feed ancestors via shraddha and tarpan. Ends at Sarvapitru Amavasya.',
    whatToDo: [
      'Daily tarpan with sesame water',
      'Shraddha on the death tithi',
      'Feed Brahmins, cow, crow, dog',
      'Avoid new ventures and shopping',
      'Recite Pitru Stotra',
    ],
    timing: 'Madhyahna kaal (12:00 to 13:30) for daily tarpan',
    fromTime: '08:00',
    toTime: '13:30',
    wish: 'May ancestors bless this family!',
    wishSub: 'Pitru Paksha 🕯️',
    checklist: [
      { id: 1, text: 'Sesame seeds (kala til)', tag: '🌾' },
      { id: 2, text: 'Kusha grass', tag: '🌿' },
      { id: 3, text: 'White rice & dahi', tag: '🍚' },
      { id: 4, text: 'Brahmin bhojan items', tag: '🍱' },
    ],
  },
  {
    id: 'sharad-navratri-day1-2026',
    name: 'Sharad Navratri Day 1',
    date: '2026-10-11',
    region: 'Hindu',
    deity: 'Maa Shailaputri',
    deityIcon: '🌸',
    tithi: 'Pratipada',
    paksha: 'Shukla',
    vara: 'Ravivara (Sunday)',
    nakshatra: 'Hasta',
    month: 'Ashwin',
    significance:
      'Most popular Navratri — 9 nights of devotion to Goddess Durga in autumn.',
    whatToDo: [
      'Ghatasthapana at sunrise',
      'Begin akhand jyoti',
      'Recite Durga Saptashati daily',
      'Observe 9-day vrat',
    ],
    timing: 'Pratahkaal — 06:15 to 09:00',
    poojaTimings: [{ label: 'Ghatasthapana', from: '06:15', to: '09:00' }],
    fromTime: '06:15',
    toTime: '09:00',
    wish: 'Jai Mata Di! Sharad Navratri begins!',
    wishSub: 'Sharad Navratri Shubhkamna 🌸',
    checklist: [
      { id: 1, text: 'Kalash & coconut', tag: '🥥' },
      { id: 2, text: 'Akhand jyoti & oil (9 days)', tag: '🪔' },
      { id: 3, text: 'Red chunari', tag: '🧵' },
      { id: 4, text: 'Marigold mala', tag: '🌼' },
      { id: 5, text: 'Durga Saptashati book', tag: '📖' },
      { id: 6, text: 'Phalahar items', tag: '🍎' },
    ],
  },
  {
    id: 'durga-ashtami-2026',
    name: 'Durga Ashtami / Mahashtami',
    date: '2026-10-18',
    region: 'Hindu',
    deity: 'Maa Mahagauri',
    deityIcon: '⚔️',
    tithi: 'Ashtami',
    paksha: 'Shukla',
    vara: 'Ravivara (Sunday)',
    nakshatra: 'Mool',
    month: 'Ashwin',
    significance:
      '8th day of Sharad Navratri — most powerful day. Worship of Maa Mahagauri. Sandhi puja transitions Ashtami to Navami.',
    whatToDo: [
      'Kanya pujan (worship 9 girls)',
      'Sandhi puja at junction of Ashtami-Navami',
      'Offer halwa, puri, chana to kanyas',
      'Recite Devi Mahatmya',
    ],
    timing: 'Sandhi Puja — last 24 mins of Ashtami + first 24 mins of Navami',
    poojaTimings: [{ label: 'Kanya Pujan', from: '08:00', to: '12:00' }],
    fromTime: '08:00',
    toTime: 'Sunset',
    wish: 'Jai Mata Di! May Maa shower blessings!',
    wishSub: 'Durga Ashtami Shubhkamna ⚔️',
    checklist: [
      { id: 1, text: 'Halwa, puri, chana', tag: '🍞' },
      { id: 2, text: 'Red dupatta for kanyas', tag: '🧣' },
      { id: 3, text: 'Bangles & gifts', tag: '🎁' },
      { id: 4, text: '9 small kalash', tag: '🏺' },
    ],
  },
  {
    id: 'sankashti-2026',
    name: 'Sankashti Chaturthi',
    date: '2026-10-29',
    region: 'Hindu',
    deity: 'Lord Ganesha',
    deityIcon: '🐘',
    tithi: 'Chaturthi',
    paksha: 'Krishna',
    vara: 'Guruvara (Thursday)',
    nakshatra: 'Pushya',
    month: 'Kartik',
    significance:
      "Monthly Ganesha vrat. Removes obstacles. Fast broken after moonrise with darshan of Chandra and Ganesha.",
    whatToDo: [
      'Day-long fast (phalahar)',
      'Offer 21 modaks',
      'Recite Sankashti katha',
      'Break fast after moonrise',
    ],
    timing: 'Sunrise to moonrise',
    vrataInfo: 'Phalahar vrat; break with chandra darshan',
    fromTime: 'Sunrise',
    toTime: 'Moonrise',
    wish: 'Ganpati Bappa Morya! Remove all sankats!',
    wishSub: 'Sankashti Chaturthi 🐘',
    checklist: [
      { id: 1, text: '21 modaks', tag: '🍬' },
      { id: 2, text: 'Durva grass', tag: '🌿' },
      { id: 3, text: 'Red flowers', tag: '🌺' },
    ],
  },
  {
    id: 'chhath-puja-2026',
    name: 'Chhath Puja (Day 1 — Nahay Khay)',
    date: '2026-11-15',
    region: 'Hindu',
    deity: 'Surya & Chhathi Maiya',
    deityIcon: '☀️',
    tithi: 'Chaturthi',
    paksha: 'Shukla',
    vara: 'Ravivara (Sunday)',
    nakshatra: 'Mool',
    month: 'Kartik',
    significance:
      '4-day festival of Bihar/UP/Jharkhand. Worship of Surya and Chhathi Maiya for family well-being. Most rigorous Hindu vrat.',
    whatToDo: [
      'Day 1 (Nahay-Khay): Holy bath, eat satvik food',
      'Day 2 (Kharna): Day-long fast, kheer-roti at sunset',
      'Day 3: Sunset arghya at river',
      'Day 4: Sunrise arghya, fast ends',
    ],
    timing: '4-day festival starts today',
    vrataInfo: '36-hour nirjala vrat on Days 2-3-4',
    fromTime: 'Sunrise',
    toTime: 'Day 4 sunrise',
    wish: 'Chhathi Maiya bless your family!',
    wishSub: 'Jai Chhathi Maiya ☀️',
    checklist: [
      { id: 1, text: 'Bamboo soop & dauri', tag: '🧺' },
      { id: 2, text: 'Thekua ingredients', tag: '🌾' },
      { id: 3, text: 'Sugarcane (5)', tag: '🌿' },
      { id: 4, text: 'Coconut, banana, fruits', tag: '🍌' },
      { id: 5, text: 'Yellow saree (laal-peeli)', tag: '👗' },
      { id: 6, text: 'Diyas for arghya', tag: '🪔' },
    ],
  },
  {
    id: 'vaikuntha-ekadashi-2026',
    name: 'Vaikuntha Ekadashi',
    date: '2026-12-30',
    region: 'Hindu',
    deity: 'Lord Vishnu',
    deityIcon: '🪷',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Budhvara (Wednesday)',
    nakshatra: 'Punarvasu',
    month: 'Margashirsha',
    significance:
      'Gates of Vaikuntha (Vishnu’s abode) open today. Crossing the Vaikuntha Dwar (north door) of temple grants moksha.',
    whatToDo: [
      'Visit Vishnu temple before sunrise',
      'Cross Vaikuntha Dwar (Uttara Dwar)',
      'Observe Ekadashi fast',
      'Recite Vishnu Sahasranama',
    ],
    timing: 'Brahma Muhurat — 04:30 to 06:00 (best for Vaikuntha Dwar)',
    fromTime: '04:30',
    toTime: 'Sunset',
    wish: 'May Lord Vishnu grant you Vaikuntha!',
    wishSub: 'Vaikuntha Ekadashi 🪷',
    checklist: [
      { id: 1, text: 'Tulsi mala', tag: '📿' },
      { id: 2, text: 'Yellow flowers', tag: '🌼' },
      { id: 3, text: 'Phalahar items', tag: '🍎' },
    ],
  }
);

// ── EKADASHIS (24 per year — fast for Vishnu) ──
PANCHANG_FESTIVALS.push(
  {
    id: 'putrada-ek-2026-1',
    name: 'Pausha Putrada Ekadashi',
    date: '2026-01-15',
    region: 'Hindu',
    deity: 'Lord Vishnu',
    deityIcon: '🪷',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Thursday',
    nakshatra: 'Rohini',
    month: 'Pausha',
    significance:
      'Fast observed by couples seeking children. "Putrada" means giver of sons. Recital of Vishnu Sahasranama is auspicious.',
    whatToDo: ['Wake before sunrise', 'Day-long phalahar fast', 'Recite Vishnu Sahasranama', 'Break fast next morning after Dwadashi tithi'],
    timing: 'Sunrise to next day sunrise',
    vrataInfo: 'Phalahar (fruits only) — no grains, no salt',
    wish: 'May Lord Vishnu bless your family!',
    wishSub: 'Shubh Putrada Ekadashi 🪷',
    checklist: [
      { id: 1, text: 'Tulsi leaves', tag: '🌿' },
      { id: 2, text: 'Phalahar items (fruits/milk)', tag: '🍎' },
      { id: 3, text: 'Yellow flowers', tag: '🌼' },
    ],
  },
  {
    id: 'shattila-ek-2026',
    name: 'Shattila Ekadashi',
    date: '2026-02-13',
    region: 'Hindu',
    deity: 'Lord Vishnu',
    deityIcon: '🌾',
    tithi: 'Ekadashi',
    paksha: 'Krishna',
    vara: 'Friday',
    nakshatra: 'Anuradha',
    month: 'Magha',
    significance:
      'Sesame (til) is used in 6 ways: bathing, donating, fire offering, eating, anointing. Frees from sins, brings prosperity.',
    whatToDo: ['Bathe with til-mixed water', 'Donate til to brahmins', 'Eat til laddoo', 'Apply til oil', 'Til homa'],
    timing: 'Sunrise to next day sunrise',
    wish: 'May the sesame offering purify you!',
    wishSub: 'Shubh Shattila Ekadashi 🌾',
    checklist: [
      { id: 1, text: 'Sesame seeds (kala til)', tag: '🌾' },
      { id: 2, text: 'Til oil & laddoo', tag: '🍬' },
    ],
  },
  {
    id: 'jaya-ek-2026',
    name: 'Jaya Ekadashi',
    date: '2026-01-29',
    region: 'Hindu',
    deity: 'Lord Vishnu',
    deityIcon: '⚜️',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Thursday',
    nakshatra: 'Ardra',
    month: 'Magha',
    significance:
      'Liberates from ghost-yoni (preta-loka). Observed for victory (jaya) in all undertakings.',
    whatToDo: ['Strict fast', 'Vishnu archana', 'Stay awake (jagran)', 'Read Padma Purana katha'],
    timing: 'Sunrise to next day sunrise',
    wish: 'May Vishnu grant victory!',
    wishSub: 'Shubh Jaya Ekadashi ⚜️',
    checklist: [{ id: 1, text: 'Tulsi & lamp', tag: '🪔' }],
  },
  {
    id: 'vijaya-ek-2026',
    name: 'Vijaya Ekadashi',
    date: '2026-02-28',
    region: 'Hindu',
    deity: 'Lord Vishnu',
    deityIcon: '🏆',
    tithi: 'Ekadashi',
    paksha: 'Krishna',
    vara: 'Saturday',
    nakshatra: 'Vishakha',
    month: 'Phalguna',
    significance:
      'Lord Rama observed this fast before crossing the ocean to Lanka. Removes obstacles, ensures success.',
    whatToDo: ['Set up Vishnu altar with kalash', 'Recite Vishnu names', 'Donate to needy'],
    timing: 'Sunrise to next day sunrise',
    wish: 'Jai Shri Ram! May victory be yours!',
    wishSub: 'Vijaya Ekadashi 🏆',
    checklist: [
      { id: 1, text: 'Kalash & coconut', tag: '🥥' },
      { id: 2, text: 'Yellow cloth', tag: '🟡' },
    ],
  },
  {
    id: 'amalaki-ek-2026',
    name: 'Amalaki Ekadashi',
    date: '2026-03-19',
    region: 'Hindu',
    deity: 'Vishnu (in Amalaki / Indian gooseberry tree)',
    deityIcon: '🌳',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Thursday',
    nakshatra: 'Revati',
    month: 'Phalguna',
    significance:
      'Worship of Amalaki (amla) tree, said to be the abode of Vishnu. Brings moksha. Falls just before Holi.',
    whatToDo: ['Visit amla tree', 'Offer water, ghee, kumkum at its base', 'Walk around it 108 times', 'Eat amla'],
    timing: 'Sunrise to next day sunrise',
    wish: 'May the Amalaki tree bless you!',
    wishSub: 'Amalaki Ekadashi 🌳',
    checklist: [
      { id: 1, text: 'Amla fruit', tag: '🟢' },
      { id: 2, text: 'Kumkum, ghee', tag: '🔴' },
    ],
  },
  {
    id: 'papamochani-2026',
    name: 'Papamochani Ekadashi',
    date: '2026-03-13',
    region: 'Hindu',
    deity: 'Lord Vishnu',
    deityIcon: '🪔',
    tithi: 'Ekadashi',
    paksha: 'Krishna',
    vara: 'Friday',
    nakshatra: 'Shravana',
    month: 'Chaitra',
    significance: '"Sin destroyer" — frees one from past papa-karma. Last Ekadashi of the lunar year.',
    whatToDo: ['Phalahar fast', 'Donate to brahmins', 'Visit Vishnu temple'],
    timing: 'Sunrise to next day sunrise',
    wish: 'May all sins be washed away',
    wishSub: 'Papamochani Ekadashi 🪔',
    checklist: [{ id: 1, text: 'Donation items', tag: '🎁' }],
  },
  {
    id: 'kamada-ek-2026',
    name: 'Kamada Ekadashi',
    date: '2026-03-28',
    region: 'Hindu',
    deity: 'Lord Vishnu',
    deityIcon: '💝',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Saturday',
    nakshatra: 'Hasta',
    month: 'Chaitra',
    significance: 'First Ekadashi of the lunar new year. "Fulfiller of desires." Free from curses.',
    whatToDo: ['Fast', 'Read Padma Purana', 'Donate clothes'],
    timing: 'Sunrise to next day sunrise',
    wish: 'May your noble wishes be fulfilled!',
    wishSub: 'Kamada Ekadashi 💝',
    checklist: [{ id: 1, text: 'Tulsi mala', tag: '📿' }],
  },
  {
    id: 'mohini-ek-2026',
    name: 'Mohini Ekadashi',
    date: '2026-04-27',
    region: 'Hindu',
    deity: 'Mohini (Vishnu’s female form)',
    deityIcon: '💃',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Monday',
    nakshatra: 'Magha',
    month: 'Vaisakha',
    significance:
      'Vishnu took the Mohini form to distribute amrita to devas during samudra-manthan. Removes all illusions (moha).',
    whatToDo: ['Strict phalahar', 'Worship Mohini-Vishnu form', 'Recite Vishnu Sahasranama'],
    timing: 'Sunrise to next day sunrise',
    wish: 'May illusions clear away!',
    wishSub: 'Mohini Ekadashi 💃',
    checklist: [{ id: 1, text: 'Phalahar items', tag: '🍎' }],
  },
  {
    id: 'devshayani-2026',
    name: 'Devshayani Ekadashi (Hari Sayan)',
    date: '2026-07-15',
    region: 'Hindu',
    deity: 'Lord Vishnu',
    deityIcon: '🛌',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Wednesday',
    nakshatra: 'Anuradha',
    month: 'Ashadha',
    significance:
      'Lord Vishnu enters yoga-nidra for 4 months (Chaturmasa). No weddings or auspicious events during this period.',
    whatToDo: [
      'Worship reclining Vishnu',
      'Begin Chaturmasa vrata',
      'Avoid new ventures, marriages',
      'Increase japa and seva',
    ],
    timing: 'Sunrise to next day sunrise',
    wish: 'Hari rests — devotion deepens!',
    wishSub: 'Devshayani Ekadashi 🛌',
    checklist: [
      { id: 1, text: 'Yellow flowers', tag: '🌼' },
      { id: 2, text: 'Camphor & ghee', tag: '🪔' },
    ],
  },
  {
    id: 'devuthani-2026',
    name: 'Devuthani Ekadashi (Prabodhini)',
    date: '2026-11-19',
    region: 'Hindu',
    deity: 'Lord Vishnu',
    deityIcon: '🌅',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Thursday',
    nakshatra: 'Uttara Ashadha',
    month: 'Kartik',
    significance:
      'Lord Vishnu awakens from yoga-nidra. Marks the end of Chaturmasa. Weddings season resumes. Tulsi Vivah follows.',
    whatToDo: [
      'Wake Vishnu with bells & conch',
      'Decorate house with rangoli',
      'Sing prabodhana stotras',
      'Begin Tulsi Vivah celebrations',
    ],
    timing: 'Brahma Muhurta — 04:30 to 05:45 (best for prabodhanam)',
    poojaTimings: [{ label: 'Prabodhana Aarti', from: '04:30', to: '06:00' }],
    wish: 'Hari has awakened! Auspicious times return!',
    wishSub: 'Devuthani Ekadashi 🌅',
    checklist: [
      { id: 1, text: 'Conch & bell', tag: '🔔' },
      { id: 2, text: 'Sugarcane stalks', tag: '🌿' },
      { id: 3, text: 'Rangoli colors', tag: '🎨' },
    ],
  },
  {
    id: 'mokshada-ek-2026',
    name: 'Mokshada Ekadashi (Gita Jayanti)',
    date: '2026-12-19',
    region: 'Hindu',
    deity: 'Krishna & Bhagavad Gita',
    deityIcon: '📖',
    tithi: 'Ekadashi',
    paksha: 'Shukla',
    vara: 'Saturday',
    nakshatra: 'Uttara Bhadrapada',
    month: 'Margashirsha',
    significance:
      'Day Lord Krishna spoke the Bhagavad Gita to Arjuna on Kurukshetra battlefield. Recitation of Gita on this day grants moksha.',
    whatToDo: [
      'Read all 18 chapters of the Gita',
      'Donate Gita books to seekers',
      'Visit Krishna temple',
      'Phalahar fast',
    ],
    timing: 'Whole day; Brahma Muhurta best for Gita parayan',
    wish: 'May the Gita illuminate your path!',
    wishSub: 'Gita Jayanti 📖',
    checklist: [
      { id: 1, text: 'Bhagavad Gita book', tag: '📖' },
      { id: 2, text: 'Tulsi mala', tag: '📿' },
      { id: 3, text: 'Yellow cloth', tag: '🟡' },
    ],
  }
);

// ── JAYANTIS ──
PANCHANG_FESTIVALS.push(
  {
    id: 'vivekananda-jayanti-2026',
    name: 'Swami Vivekananda Jayanti',
    date: '2026-01-12',
    region: 'Hindu',
    deity: 'Swami Vivekananda',
    deityIcon: '🧘',
    tithi: '—',
    vara: 'Monday',
    nakshatra: '—',
    month: 'January',
    significance:
      'Birth of Swami Vivekananda (1863), spiritual leader who introduced Vedanta and Yoga to the West. Celebrated as National Youth Day.',
    whatToDo: [
      'Read Vivekananda\'s "Karma Yoga" / "Raja Yoga"',
      'Reflect on his Chicago address',
      'Engage in seva (selfless service)',
      'Visit Belur Math (if possible)',
    ],
    timing: 'Whole day',
    wish: 'Arise, awake, and stop not till the goal is reached!',
    wishSub: 'Vivekananda Jayanti 🧘',
    checklist: [{ id: 1, text: 'Vivekananda book', tag: '📖' }],
  },
  {
    id: 'shani-jayanti-2026',
    name: 'Shani Jayanti',
    date: '2026-05-16',
    region: 'Hindu',
    deity: 'Lord Shani (Saturn)',
    deityIcon: '🪐',
    tithi: 'Amavasya',
    paksha: 'Krishna',
    vara: 'Saturday',
    nakshatra: 'Krittika',
    month: 'Vaisakha',
    significance:
      'Birth of Lord Shani Dev, son of Surya & Chhaya. Lord of justice and karma. Worship pacifies Sade Sati / Dhaiya doshas.',
    whatToDo: [
      'Visit a Shani temple',
      'Offer mustard oil to Shani idol',
      'Wear black clothes',
      'Recite Shani Chalisa / Dasharatha Krita Shani Stotra',
      'Donate black sesame, urad dal, iron, black umbrella',
      'Feed crows (Shani vahana)',
    ],
    timing: 'Whole day; evening sandhya kaal best (16:30 to 19:00)',
    poojaTimings: [{ label: 'Pradosh Kaal (best)', from: '16:30', to: '19:00' }],
    wish: 'Shani Dev bless you with patience & justice!',
    wishSub: 'Shani Jayanti 🪐',
    checklist: [
      { id: 1, text: 'Mustard oil (sarson tel)', tag: '🛢️' },
      { id: 2, text: 'Black sesame seeds', tag: '🌾' },
      { id: 3, text: 'Black cloth / clothes', tag: '⬛' },
      { id: 4, text: 'Urad dal', tag: '🫘' },
      { id: 5, text: 'Iron items (horseshoe, nail)', tag: '⚙️' },
      { id: 6, text: 'Black umbrella for daan', tag: '☂️' },
    ],
  },
  {
    id: 'narasimha-jayanti-2026',
    name: 'Narasimha Jayanti',
    date: '2026-05-21',
    region: 'Hindu',
    deity: 'Lord Narasimha',
    deityIcon: '🦁',
    tithi: 'Chaturdashi',
    paksha: 'Shukla',
    vara: 'Thursday',
    nakshatra: 'Swati',
    month: 'Vaisakha',
    significance:
      "Vishnu's 4th avatar (half-man, half-lion). Killed demon Hiranyakashipu to save devotee Prahlada. Removes fear, grants protection.",
    whatToDo: [
      'Strict fast till evening',
      'Sandhya kaal puja (when Narasimha appeared)',
      'Read Narasimha Kavacha',
      'Offer panchamrita and bel patra',
    ],
    timing: 'Sandhya Kaal — 17:30 to 19:30 (when Narasimha killed Hiranyakashipu)',
    poojaTimings: [{ label: 'Narasimha Avatar Time', from: '17:30', to: '19:30' }],
    wish: 'Jai Narasimha! May He protect from all evil!',
    wishSub: 'Narasimha Jayanti 🦁',
    checklist: [
      { id: 1, text: 'Panchamrit (5 nectars)', tag: '🥛' },
      { id: 2, text: 'Bel patra', tag: '🍃' },
      { id: 3, text: 'Yellow & red flowers', tag: '🌹' },
      { id: 4, text: 'Phalahar', tag: '🍎' },
    ],
  },
  {
    id: 'parashurama-jayanti-2026',
    name: 'Parashurama Jayanti',
    date: '2026-04-20',
    region: 'Hindu',
    deity: 'Lord Parashurama',
    deityIcon: '🪓',
    tithi: 'Tritiya',
    paksha: 'Shukla',
    vara: 'Monday',
    nakshatra: 'Rohini',
    month: 'Vaisakha',
    significance:
      "Birth of Vishnu's 6th avatar — Parashurama, the warrior-brahmin who eliminated tyrannical kshatriyas. Falls on Akshaya Tritiya.",
    whatToDo: ['Recite Parashurama Stotra', 'Visit a Parashurama temple', 'Donate weapons or tools to needy artisans'],
    timing: 'Pratahkaal — sunrise to 12:00',
    wish: 'May valor and dharma guide you!',
    wishSub: 'Parashurama Jayanti 🪓',
    checklist: [{ id: 1, text: 'Yellow flowers', tag: '🌼' }],
  },
  {
    id: 'adi-shankara-2026',
    name: 'Adi Shankaracharya Jayanti',
    date: '2026-05-13',
    region: 'Hindu',
    deity: 'Adi Shankaracharya',
    deityIcon: '🕉️',
    tithi: 'Panchami',
    paksha: 'Shukla',
    vara: 'Wednesday',
    nakshatra: 'Pushya',
    month: 'Vaisakha',
    significance:
      'Birth of Adi Shankara (788 CE), the great philosopher who established Advaita Vedanta and founded 4 mathas.',
    whatToDo: [
      'Read his works (Vivekachudamani, Bhaja Govindam)',
      'Visit Sringeri / Dwaraka / Puri / Joshimath matha',
      'Reflect on "Brahma Satyam Jagan Mithya"',
    ],
    timing: 'Whole day',
    wish: 'Tat Tvam Asi — That Thou Art!',
    wishSub: 'Shankara Jayanti 🕉️',
    checklist: [{ id: 1, text: 'Bhaja Govindam book', tag: '📖' }],
  },
  {
    id: 'dattatreya-jayanti-2026',
    name: 'Dattatreya Jayanti',
    date: '2026-12-22',
    region: 'Hindu',
    deity: 'Lord Dattatreya',
    deityIcon: '👳',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Tuesday',
    nakshatra: 'Mrigashira',
    month: 'Margashirsha',
    significance:
      'Combined incarnation of Brahma-Vishnu-Shiva, born to Atri & Anasuya. Adi-Guru of all sects. Worshipped widely in Maharashtra & Karnataka.',
    whatToDo: [
      'Visit Audumbar / Narsobawadi / Ganagapur temples',
      'Recite Dattatreya Stotra',
      'Read Avadhuta Gita',
      'Feed brahmins and dogs (Datta\'s companions)',
    ],
    timing: 'Sandhya Kaal — 17:00 to 19:00',
    wish: 'Jai Guru Datta!',
    wishSub: 'Dattatreya Jayanti 👳',
    checklist: [
      { id: 1, text: 'Audumbar (fig) leaves', tag: '🍃' },
      { id: 2, text: 'White flowers', tag: '🌼' },
      { id: 3, text: 'Sweets for dogs', tag: '🐕' },
    ],
  },
  {
    id: 'kal-bhairav-jayanti-2026',
    name: 'Kal Bhairav Jayanti',
    date: '2026-12-06',
    region: 'Hindu',
    deity: 'Kal Bhairav',
    deityIcon: '🗡️',
    tithi: 'Ashtami',
    paksha: 'Krishna',
    vara: 'Sunday',
    nakshatra: 'Magha',
    month: 'Margashirsha',
    significance:
      'Fierce form of Shiva, lord of time (Kal). Removes negativity, protects from black magic, sudden misfortune.',
    whatToDo: [
      'Visit Bhairav temple at night',
      'Offer mustard oil, jalebi, rabri',
      'Light black sesame oil lamp',
      'Feed black dogs',
      'Recite Bhairav Ashtak / Chalisa',
    ],
    timing: 'Madhya Ratri (midnight)',
    poojaTimings: [{ label: 'Midnight Puja', from: '23:30', to: '01:00' }],
    wish: 'Jai Kala Bhairav! Remove all sankats!',
    wishSub: 'Kala Bhairav Jayanti 🗡️',
    checklist: [
      { id: 1, text: 'Mustard oil', tag: '🛢️' },
      { id: 2, text: 'Jalebi & rabri', tag: '🍬' },
      { id: 3, text: 'Black dog food', tag: '🐕' },
    ],
  },
  {
    id: 'valmiki-jayanti-2026',
    name: 'Valmiki Jayanti (Pragat Diwas)',
    date: '2026-10-25',
    region: 'Hindu',
    deity: 'Maharishi Valmiki',
    deityIcon: '✍️',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Sunday',
    nakshatra: 'Ashwini',
    month: 'Ashwin',
    significance:
      'Birth of Maharishi Valmiki, author of the Ramayana. The "Adi Kavi" (first poet). Celebrated across India, especially by the Valmiki community.',
    whatToDo: [
      'Read Ramayana / Yuddha Kanda',
      'Recite "Sri Ram Jai Ram"',
      'Visit Valmiki temple',
      'Donate books to schools',
    ],
    timing: 'Whole day',
    wish: 'Jai Maharishi Valmiki!',
    wishSub: 'Valmiki Jayanti ✍️',
    checklist: [{ id: 1, text: 'Ramayana book', tag: '📖' }],
  },
  {
    id: 'tulsidas-jayanti-2026',
    name: 'Tulsidas Jayanti',
    date: '2026-08-19',
    region: 'Hindu',
    deity: 'Goswami Tulsidas',
    deityIcon: '📜',
    tithi: 'Saptami',
    paksha: 'Shukla',
    vara: 'Wednesday',
    nakshatra: 'Swati',
    month: 'Shravan',
    significance:
      'Birth of Goswami Tulsidas, author of Ramcharitmanas. Greatest devotee-poet of Lord Rama.',
    whatToDo: ['Read Ramcharitmanas (Sundar Kand)', 'Sing Hanuman Chalisa (also by Tulsidas)', 'Visit Sankat Mochan temple'],
    timing: 'Whole day',
    wish: 'Jai Shri Ram!',
    wishSub: 'Tulsidas Jayanti 📜',
    checklist: [{ id: 1, text: 'Ramcharitmanas', tag: '📖' }],
  }
);

// ── REGIONAL NEW YEARS & FESTIVALS ──
PANCHANG_FESTIVALS.push(
  {
    id: 'lohri-2026',
    name: 'Lohri',
    date: '2026-01-13',
    region: 'Hindu',
    deity: 'Agni Dev (Fire)',
    deityIcon: '🔥',
    tithi: '—',
    vara: 'Tuesday',
    nakshatra: '—',
    month: 'Pausha',
    significance:
      'Punjab harvest festival, day before Makar Sankranti. Bonfire celebrating end of winter solstice. Special for newlyweds and newborn babies.',
    whatToDo: [
      'Light bonfire after sunset',
      'Throw til, gud, popcorn, peanuts in fire',
      'Sing Lohri songs (Sundari Mundari)',
      'Bhangra/Giddha around the fire',
    ],
    timing: 'Sunset onwards',
    wish: 'Sundri Mundri ho!',
    wishSub: 'Happy Lohri 🔥',
    checklist: [
      { id: 1, text: 'Til, gud, peanuts, popcorn', tag: '🌾' },
      { id: 2, text: 'Firewood (for bonfire)', tag: '🪵' },
      { id: 3, text: 'Rewari & gajak', tag: '🍬' },
    ],
  },
  {
    id: 'vishu-2026',
    name: 'Vishu (Kerala New Year)',
    date: '2026-04-14',
    region: 'Hindu',
    deity: 'Lord Krishna (Guruvayur)',
    deityIcon: '🌻',
    tithi: 'Pratipada',
    paksha: 'Shukla',
    vara: 'Tuesday',
    nakshatra: 'Bharani',
    month: 'Medam (Malayalam)',
    significance:
      'Malayalam New Year. Sun enters Mesha rashi. "Vishu Kani" — first sight on this day determines the year ahead.',
    whatToDo: [
      'Arrange Vishu Kani (mirror, gold, rice, fruits, kanikonna flowers) night before',
      'Wake at dawn and view kani with closed eyes',
      'Give kaineetam (cash gifts) to younger family',
      'Visit Krishna temple',
    ],
    timing: 'Dawn (~5:30 AM) — first sight of kani',
    wish: 'Vishu Aashamsakal!',
    wishSub: 'Happy Vishu 🌻',
    checklist: [
      { id: 1, text: 'Kanikonna (yellow flowers)', tag: '🌼' },
      { id: 2, text: 'Mirror', tag: '🪞' },
      { id: 3, text: 'Gold coins / jewellery', tag: '🪙' },
      { id: 4, text: 'Fruits, rice, vegetables', tag: '🍎' },
      { id: 5, text: 'Coins for kaineetam', tag: '💰' },
    ],
  },
  {
    id: 'bihu-2026',
    name: 'Rongali Bihu (Assamese New Year)',
    date: '2026-04-14',
    region: 'Hindu',
    deity: 'Surya & Mother Goddess',
    deityIcon: '🌾',
    tithi: 'Pratipada',
    paksha: 'Shukla',
    vara: 'Tuesday',
    nakshatra: 'Bharani',
    month: 'Bohag (Assamese)',
    significance:
      'Assamese New Year / spring harvest festival. Marks beginning of sowing season. 7-day celebration.',
    whatToDo: [
      'Cow Bihu (wash and decorate cattle)',
      'Wear traditional gamosa',
      'Sing Bihu Geet, dance Bihu',
      'Cook pitha and laru',
    ],
    timing: '7-day festival begins',
    wish: 'Subho Bihu!',
    wishSub: 'Rongali Bihu 🌾',
    checklist: [
      { id: 1, text: 'Gamosa (Assamese towel)', tag: '🧣' },
      { id: 2, text: 'Pitha & laru ingredients', tag: '🥥' },
    ],
  },
  {
    id: 'onam-2026',
    name: 'Thiruvonam (Onam main day)',
    date: '2026-08-26',
    region: 'Hindu',
    deity: 'King Mahabali & Vamana',
    deityIcon: '🌸',
    tithi: 'Dwadashi',
    paksha: 'Shukla',
    vara: 'Wednesday',
    nakshatra: 'Shravana (Thiruvonam)',
    month: 'Chingam (Malayalam)',
    significance:
      'Kerala\'s biggest festival. Welcomes the legendary King Mahabali who returns to visit his subjects once a year.',
    whatToDo: [
      'Create Pookalam (flower carpet) — 10 days running up',
      'Wear new mundu / set saree',
      'Prepare Onam Sadhya (26-dish feast on banana leaf)',
      'Watch Vallam Kali (boat races)',
      'Pulikali tiger dance',
    ],
    timing: 'Whole day; sadhya at noon',
    wish: 'Onam Ashamsakal!',
    wishSub: 'Happy Onam 🌸',
    checklist: [
      { id: 1, text: 'Flowers (10 colors for pookalam)', tag: '🌺' },
      { id: 2, text: 'Banana leaves', tag: '🍃' },
      { id: 3, text: 'Sadhya ingredients (rice, sambar, avial)', tag: '🍚' },
      { id: 4, text: 'New kasavu mundu / saree', tag: '👗' },
      { id: 5, text: 'Payasam ingredients', tag: '🥛' },
    ],
  }
);

// ── ADDITIONAL VRATAS & FESTIVALS ──
PANCHANG_FESTIVALS.push(
  {
    id: 'sheetala-ashtami-2026',
    name: 'Sheetala Ashtami (Basoda)',
    date: '2026-03-21',
    region: 'Hindu',
    deity: 'Maa Sheetala',
    deityIcon: '🌸',
    tithi: 'Ashtami',
    paksha: 'Krishna',
    vara: 'Saturday',
    nakshatra: 'Anuradha',
    month: 'Chaitra',
    significance:
      'Goddess of cool — protects from smallpox, chicken pox, measles. Only stale (basi) food is offered; no cooking that day.',
    whatToDo: [
      'Cook food the previous night',
      'Eat only "basoda" (stale food) — no fire that day',
      'Bathe in cold water',
      'Offer cool food to Sheetala Mata',
    ],
    timing: 'Whole day; pratahkaal puja best',
    vrataInfo: 'Cold-food vrat — no fresh cooking',
    wish: 'May Sheetala Mata keep you healthy!',
    wishSub: 'Sheetala Ashtami 🌸',
    checklist: [
      { id: 1, text: 'Pakoras, halwa (cooked night before)', tag: '🥧' },
      { id: 2, text: 'Curd, raita', tag: '🥛' },
      { id: 3, text: 'Cold water, neem leaves', tag: '🌿' },
    ],
  },
  {
    id: 'hartalika-teej-2026',
    name: 'Hartalika Teej',
    date: '2026-09-14',
    region: 'Hindu',
    deity: 'Maa Parvati & Shiva',
    deityIcon: '🌺',
    tithi: 'Tritiya',
    paksha: 'Shukla',
    vara: 'Monday',
    nakshatra: 'Hasta',
    month: 'Bhadrapada',
    significance:
      'Maa Parvati did intense tapasya to win Shiva as husband. Married women fast for spouse\'s long life; unmarried for a good husband.',
    whatToDo: [
      'Wake before sunrise',
      'Nirjala (waterless) fast',
      'Worship sand idols of Shiva-Parvati',
      'Listen to Hartalika katha',
      'Stay awake at night singing bhajans',
    ],
    timing: 'Pratahkaal (morning) puja',
    vrataInfo: 'Nirjala vrat — most demanding women\'s vrat',
    wish: 'Maa Parvati bless your marriage!',
    wishSub: 'Hartalika Teej 🌺',
    checklist: [
      { id: 1, text: 'Sand & clay (for idols)', tag: '🏺' },
      { id: 2, text: 'Mehndi cone', tag: '💚' },
      { id: 3, text: 'Green saree & bangles', tag: '👗' },
      { id: 4, text: 'Bel patra & dhatura', tag: '🍃' },
      { id: 5, text: '16 shringar items', tag: '💄' },
    ],
  },
  {
    id: 'rishi-panchami-2026',
    name: 'Rishi Panchami',
    date: '2026-09-15',
    region: 'Hindu',
    deity: 'Sapta Rishis',
    deityIcon: '🌟',
    tithi: 'Panchami',
    paksha: 'Shukla',
    vara: 'Tuesday',
    nakshatra: 'Chitra',
    month: 'Bhadrapada',
    significance:
      'Worship of the 7 great sages (Kashyapa, Atri, Bharadwaja, Vishvamitra, Gautama, Jamadagni, Vasishtha). Removes any inadvertent rajaswala-related impurity.',
    whatToDo: [
      'Bathe with apamarga leaves before sunrise',
      'Worship 7 rishis on a kalash',
      'Eat sama rice and curd (no salt)',
      'Donate to brahmins',
    ],
    timing: 'Madhyahna kaal — 11:30 to 13:00',
    wish: 'Sapta Rishis bless your family!',
    wishSub: 'Rishi Panchami 🌟',
    checklist: [
      { id: 1, text: 'Apamarga leaves', tag: '🌿' },
      { id: 2, text: 'Sama rice & curd', tag: '🍚' },
      { id: 3, text: 'White cloth', tag: '⬜' },
    ],
  },
  {
    id: 'ahoi-ashtami-2026',
    name: 'Ahoi Ashtami',
    date: '2026-10-30',
    region: 'Hindu',
    deity: 'Maa Ahoi (Parvati)',
    deityIcon: '🌖',
    tithi: 'Ashtami',
    paksha: 'Krishna',
    vara: 'Friday',
    nakshatra: 'Punarvasu',
    month: 'Kartik',
    significance:
      'Mothers fast for the long life and prosperity of their children. Break fast on seeing stars or moon.',
    whatToDo: [
      'Wake before sunrise',
      'Nirjala vrat all day',
      'Listen to Ahoi katha in evening',
      'Worship Ahoi Mata on wall painting',
      'Break fast after star/moon sighting',
    ],
    timing: 'Sunrise to moonrise (or star sighting)',
    vrataInfo: 'Nirjala vrat',
    wish: 'May your children live long and prosper!',
    wishSub: 'Ahoi Ashtami 🌖',
    checklist: [
      { id: 1, text: 'Karwa / clay pot', tag: '🏺' },
      { id: 2, text: 'Sieve (chalni)', tag: '🪞' },
      { id: 3, text: 'Roli, rice, water', tag: '🔴' },
      { id: 4, text: 'Sweets & dry fruits', tag: '🍬' },
    ],
  },
  {
    id: 'skanda-sashti-2026',
    name: 'Skanda Sashti / Kanda Sashti',
    date: '2026-10-24',
    region: 'Hindu',
    deity: 'Lord Murugan (Kartikeya)',
    deityIcon: '🦚',
    tithi: 'Sashti',
    paksha: 'Shukla',
    vara: 'Saturday',
    nakshatra: 'Mool',
    month: 'Ashwin',
    significance:
      'Day Lord Murugan defeated demon Soorapadman. Most observed in Tamil Nadu — 6-day vrat ending with Soorasamharam at Tiruchendur.',
    whatToDo: [
      '6-day fast (begins on Krishna Amavasya)',
      'Visit Murugan / Subrahmanya temple',
      'Recite Skanda Sashti Kavasam',
      'Watch Soorasamharam ritual',
    ],
    timing: 'Sunrise to sunset',
    wish: 'Vetri Vel Muruganukku Arohara!',
    wishSub: 'Skanda Sashti 🦚',
    checklist: [
      { id: 1, text: 'Vel (small spear)', tag: '🔱' },
      { id: 2, text: 'Yellow flowers', tag: '🌼' },
      { id: 3, text: 'Coconut & milk', tag: '🥥' },
    ],
  },
  {
    id: 'vaikuntha-chaturdashi-2026',
    name: 'Vaikuntha Chaturdashi',
    date: '2026-11-23',
    region: 'Hindu',
    deity: 'Shiva & Vishnu (united)',
    deityIcon: '🤝',
    tithi: 'Chaturdashi',
    paksha: 'Shukla',
    vara: 'Monday',
    nakshatra: 'Krittika',
    month: 'Kartik',
    significance:
      "Unique day when Vishnu transfers control of the worlds to Shiva. Both deities are worshipped together. Bilva leaves to Vishnu, lotus to Shiva — role reversal.",
    whatToDo: [
      'Offer bilva to Vishnu (with conch & chakra)',
      'Offer lotus to Shiva',
      'Read Kashi Khand',
      'Light 14 lamps',
    ],
    timing: 'Nishita Kaal — midnight 23:30 to 00:30',
    wish: 'Hari and Hara are one!',
    wishSub: 'Vaikuntha Chaturdashi 🤝',
    checklist: [
      { id: 1, text: 'Bilva leaves', tag: '🍃' },
      { id: 2, text: 'Lotus flowers', tag: '🪷' },
      { id: 3, text: '14 oil lamps', tag: '🪔' },
    ],
  },
  {
    id: 'karthigai-deepam-2026',
    name: 'Karthigai Deepam',
    date: '2026-12-04',
    region: 'Hindu',
    deity: 'Lord Shiva (Jyoti Linga)',
    deityIcon: '🕯️',
    tithi: 'Purnima',
    paksha: 'Shukla',
    vara: 'Friday',
    nakshatra: 'Krittika',
    month: 'Kartik / Karthigai',
    significance:
      'Tamil festival — Shiva appeared as Jyotirlingam (column of light) at Tiruvannamalai. Hilltop fire (Mahadeepam) burns for days.',
    whatToDo: [
      'Light multiple lamps (deepa) at home',
      'Walk around Arunachala mountain (Girivalam)',
      'Watch Mahadeepam at Tiruvannamalai',
      'Light kalyana deepam in family',
    ],
    timing: 'Sandhya kaal — 18:00 onwards',
    wish: 'Arunachaleshwara! Shiva is endless light!',
    wishSub: 'Karthigai Deepam 🕯️',
    checklist: [
      { id: 1, text: 'Brass lamps (many)', tag: '🪔' },
      { id: 2, text: 'Sesame oil', tag: '🛢️' },
      { id: 3, text: 'Cotton wicks', tag: '🧵' },
      { id: 4, text: 'Maavilakku (rice flour lamp)', tag: '🌾' },
    ],
  },
  {
    id: 'vishwakarma-puja-2026',
    name: 'Vishwakarma Puja',
    date: '2026-09-17',
    region: 'Hindu',
    deity: 'Lord Vishwakarma',
    deityIcon: '🔨',
    tithi: 'Sankranti',
    vara: 'Thursday',
    nakshatra: 'Hasta',
    month: 'Kanya Sankranti',
    significance:
      "Divine architect & celestial engineer. Worshipped by artisans, craftsmen, mechanics, factory workers, engineers. Workplace puja day.",
    whatToDo: [
      'Clean and decorate workplace/tools',
      'Place Vishwakarma idol/photo',
      'Offer flowers, sweets, dhoop',
      'Don\'t work that day (let tools rest)',
    ],
    timing: 'Pratahkaal — 08:00 to 12:00',
    wish: 'May your craft and work flourish!',
    wishSub: 'Vishwakarma Puja 🔨',
    checklist: [
      { id: 1, text: 'Vishwakarma photo / idol', tag: '🙏' },
      { id: 2, text: 'Flowers & garland', tag: '🌺' },
      { id: 3, text: 'Sweets (laddoo)', tag: '🍬' },
      { id: 4, text: 'New tools/equipment', tag: '🔧' },
    ],
  },
  {
    id: 'shravan-somvar-2026-1',
    name: 'Shravan Somvar (1st Monday)',
    date: '2026-08-10',
    region: 'Hindu',
    deity: 'Lord Shiva',
    deityIcon: '🔱',
    tithi: 'Saptami',
    paksha: 'Shukla',
    vara: 'Monday',
    nakshatra: 'Vishakha',
    month: 'Shravan',
    significance:
      'Mondays in Shravan month are most sacred to Shiva. Devotees do Rudrabhishek with milk. Unmarried women fast for a good husband.',
    whatToDo: [
      'Bath before sunrise',
      'Visit Shiva temple — offer Gangajal/milk on Shivling',
      'Offer bel patra (3-leaf)',
      'Fast (phalahar)',
      'Wear green clothes',
    ],
    timing: 'Pradosh kaal best — 17:30 to 19:30',
    poojaTimings: [{ label: 'Rudrabhishek', from: '06:00', to: '09:00' }],
    wish: 'Har Har Mahadev! Bhole Baba bless you!',
    wishSub: 'Shravan Somvar 🔱',
    checklist: [
      { id: 1, text: 'Gangajal / milk', tag: '🥛' },
      { id: 2, text: 'Bel patra (lots)', tag: '🍃' },
      { id: 3, text: 'Dhatura, sandal', tag: '🌸' },
      { id: 4, text: 'White flowers', tag: '🌼' },
      { id: 5, text: 'Green clothes', tag: '💚' },
    ],
  },
  {
    id: 'pradosh-vrat-monthly',
    name: 'Pradosh Vrat (Monthly)',
    date: '2026-05-28',
    region: 'Hindu',
    deity: 'Lord Shiva',
    deityIcon: '🌙',
    tithi: 'Trayodashi',
    paksha: 'Shukla',
    vara: 'Thursday',
    nakshatra: 'Hasta',
    month: 'Vaisakha',
    significance:
      'Falls on 13th tithi (twice a month). Worship at sandhya kaal removes all sins. Saturday Pradosh is most powerful.',
    whatToDo: ['Fast all day', 'Bath before sunset', 'Visit Shiva temple at pradosh kaal', 'Offer bel patra and water'],
    timing: 'Pradosh Kaal — 45 min before to 45 min after sunset',
    poojaTimings: [{ label: 'Pradosh Kaal Puja', from: '17:30', to: '19:00' }],
    wish: 'May Shiva remove all sins!',
    wishSub: 'Shubh Pradosh 🌙',
    checklist: [
      { id: 1, text: 'Bel patra', tag: '🍃' },
      { id: 2, text: 'Milk, gangajal', tag: '🥛' },
    ],
  },
  {
    id: 'somvati-amavasya-2026',
    name: 'Somvati Amavasya',
    date: '2026-08-31',
    region: 'Hindu',
    deity: 'Pitru / Lord Shiva',
    deityIcon: '🌑',
    tithi: 'Amavasya',
    paksha: 'Krishna',
    vara: 'Monday',
    nakshatra: 'Magha',
    month: 'Shravan',
    significance:
      'Rare — Amavasya falling on Monday. Married women observe vrat for husband\'s long life. Pitru tarpana is auspicious.',
    whatToDo: [
      'Holy bath in sacred river',
      'Pitru tarpana',
      'Pradakshina of Peepal tree (108 times)',
      'Donate til, gud, blankets',
    ],
    timing: 'Pratahkaal — 06:00 to 12:00',
    wish: 'Ancestors bless the family!',
    wishSub: 'Somvati Amavasya 🌑',
    checklist: [
      { id: 1, text: 'Sesame seeds', tag: '🌾' },
      { id: 2, text: 'White flowers', tag: '🌼' },
      { id: 3, text: 'Peepal puja items', tag: '🌳' },
    ],
  }
);

export const REGIONS = ['All', 'Hindu', 'Sikh', 'Muslim', 'Christian'] as const;
